## Analyze POPS complaint detail

### scrape by BeautifulSoup(failed)

In [25]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
complaint_numbers = pd.read_csv('complaint_number.csv')
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36" 
}

#results = []
for complaint_no in complaint_number['complaint_number']:
    url = f'https://a810-bisweb.nyc.gov/bisweb/OverviewForComplaintServlet?complaintno={complaint_no}'
    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.text, 'html.parser')
    #text = soup.get_text(' ', strip=True)
    #result = {}
    #result['complaint_no'] = complaint_no
    #result['text'] = text
    #results.append(result)
#df = pd.DataFrame(results)
soup

KeyboardInterrupt:

### import complaint number

In [2]:
import pandas as pd
complaint_number = pd.read_csv('complaint_number.csv')
complaint_number

    complaint_number
0            1462915
1            1633608
2            1472559
3            1527139
4            1468464
..               ...
579          3A27969
580          3918419
581          3796731
582          3A01737
583          3826753

[584 rows x 1 columns]

In [8]:
print(response.status_code)
print(response.headers)

200
{'Server': 'AkamaiGHost', 'Mime-Version': '1.0', 'Content-Type': 'text/html', 'Content-Length': '418', 'Expires': 'Mon, 06 Jul 2026 13:55:52 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Mon, 06 Jul 2026 13:55:52 GMT', 'Connection': 'close', 'Set-Cookie': 'akavpwr_wr=1783346157~id=1c880a8cad2e8342494da4039f402e6c; Expires=Mon, 06 Jul 2026 13:55:57 GMT; Path=/; HttpOnly; Secure; SameSite=None'}

In [9]:
print(response.text[:500])

<HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>

You don't have permission to access "http&#58;&#47;&#47;a810&#45;bisweb&#46;nyc&#46;gov&#47;bisweb&#47;OverviewForComplaintServlet&#63;" on this server.<P>
Reference&#32;&#35;18&#46;1a593a17&#46;1783346152&#46;24f2b3d
<P>https&#58;&#47;&#47;errors&#46;edgesuite&#46;net&#47;18&#46;1a593a17&#46;1783346152&#46;24f2b3d</P>
</BODY>
</HTML>

In [10]:
response = requests.get(url, headers=headers)

print(response.cookies)
print(response.headers)

<RequestsCookieJar[<Cookie akavpau_wr=1783346888~id=a69b12d926a4a6d6a6e03be088448fac for a810-bisweb.nyc.gov/>]>
{'Server': 'AkamaiGHost', 'Mime-Version': '1.0', 'Content-Type': 'text/html', 'Content-Length': '420', 'Expires': 'Mon, 06 Jul 2026 14:03:08 GMT', 'Date': 'Mon, 06 Jul 2026 14:03:08 GMT', 'Connection': 'close', 'Set-Cookie': 'akavpau_wr=1783346888~id=a69b12d926a4a6d6a6e03be088448fac; Path=/; HttpOnly; Secure; SameSite=None'}

### scrape by playwight(failed)

In [11]:
!pip install playwright

Requirement already satisfied: playwright in /Users/kunihiro-iwasaki/.venvs/lede/lib/python3.13/site-packages (1.60.0)
Requirement already satisfied: pyee<14,>=13 in /Users/kunihiro-iwasaki/.venvs/lede/lib/python3.13/site-packages (from playwright) (13.0.1)
Requirement already satisfied: greenlet<4.0.0,>=3.1.1 in /Users/kunihiro-iwasaki/.venvs/lede/lib/python3.13/site-packages (from playwright) (3.5.1)
Requirement already satisfied: typing-extensions in /Users/kunihiro-iwasaki/.venvs/lede/lib/python3.13/site-packages (from pyee<14,>=13->playwright) (4.15.0)

In [13]:
!playwright install

In [14]:
from playwright.sync_api import sync_playwright

complaint_no = 1721121

url = (
    "https://a810-bisweb.nyc.gov/bisweb/"
    f"OverviewForComplaintServlet?complaintno={complaint_no}"
)

with sync_playwright() as p:

    browser = p.chromium.launch(headless=False)

    page = browser.new_page()

    page.goto(url)

    page.wait_for_load_state("networkidle")

    print(page.title())

    html = page.content()

    with open("test.html", "w", encoding="utf-8") as f:
        f.write(html)

    browser.close()

Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.

In [16]:
from playwright.async_api import async_playwright

async def main():

    complaint_no = 1721121

    url = (
        "https://a810-bisweb.nyc.gov/bisweb/"
        f"OverviewForComplaintServlet?complaintno={complaint_no}"
    )

    async with async_playwright() as p:

        browser = await p.chromium.launch(
            headless=False
        )

        page = await browser.new_page()

        await page.goto(url)

        await page.wait_for_load_state(
            "networkidle"
        )

        print(await page.title())

        html = await page.content()

        with open(
            "test.html",
            "w",
            encoding="utf-8"
        ) as f:
            f.write(html)

        await browser.close()

await main()

Overview for Complaint #:1721121 = RESOLVED

In [18]:
from playwright.async_api import async_playwright

async def main():

    complaint_no = 1721121

    url = (
        "https://a810-bisweb.nyc.gov/bisweb/"
        f"OverviewForComplaintServlet?complaintno={complaint_no}"
    )

    async with async_playwright() as p:

        browser = await p.chromium.launch(
            headless=False
        )

        page = await browser.new_page()

        await page.goto(url)

        await page.wait_for_load_state(
            "networkidle"
        )

        print("タイトル:")
        print(await page.title())

        html = await page.content()

        # HTML保存
        with open(
            "test.html",
            "w",
            encoding="utf-8"
        ) as f:
            f.write(html)

        # -------------------------
        # BeautifulSoupで本文取得
        # -------------------------
        soup = BeautifulSoup(
            html,
            "html.parser"
        )

        text = soup.get_text(
            "\n",
            strip=True
        )

        print("\n===== ページ本文 =====")
        print(text[:5000])

        await browser.close()

await main()

タイトル:
Overview for Complaint #:1721121 = RESOLVED

===== ページ本文 =====
Overview for Complaint #:1721121 = RESOLVED
BIS Menu
|  Complaint
FAQs
|
Glossary
Jul 7, 2026
NYC Department of Buildings
Overview for Complaint #:1721121 = RESOLVED
Complaint at:  200 EAST 24 STREET
BIN:
1019782
Borough: MANHATTAN
ZIP: 10010
Re:  There is a POPS that should be open. The time posted is 8am8pm or dark. There is a fence around it and the gate is locked shut.No damage.
Category Code:
78      PRIVATELY OWNED PUBLIC SPACE/NON-COMPLIANCE
PRIVATELY OWNED PUBLIC SPACE : CLOSED DURING OPEN HOURS
Assigned To:
QUALITY ASSURANCE UNIT
Priority:
B
311 Reference Number:
311-26988633
Received:
03/31/2026
Block:
904
Lot:
50
Community Board:
106
Owner:
CRYSTAL HOUSE OWNERS INC C/O M
Last Inspection:
04/16/2026 -  - BY BADGE # 2570
Disposition:
04/17/2026 - I2 - NO VIOLATION WARRANTED FOR COMPLAINT AT TIME OF INSPECTION
Comments:
SITE APPEARS TO ACCESSIBLE AND OPEN TO THE PUBLIC. SIGNAGE POSTED.
Complaint Disposition History
#
Disposition
Disposition
Inspection
Date
Date
Code
By
If you have any questions please review these
Frequently Asked Questions
,
	the
Glossary
, or
	call the 311 Citizen Service Center by dialing 311 or (212) NEW YORK outside of New York City.
BIS Menu
|  Complaint
Privacy Policy
Terms of Use

### scrape by playwright(succeed)

In [40]:
import random
import asyncio
import re

In [44]:
from playwright.async_api import async_playwright

async def main():
    
    complaint_numbers = pd.read_csv('complaint_number.csv')

    results = []

    async with async_playwright() as p:

        browser = await p.chromium.launch(
            headless=False
        )

        page = await browser.new_page()

        for complaint_no in complaint_numbers['complaint_number']:
            url = (
            "https://a810-bisweb.nyc.gov/bisweb/"
            f"OverviewForComplaintServlet?complaintno={complaint_no}"
        )
            page = await browser.new_page()
            try:
                await page.goto(url, wait_until='domcontentloaded', timeout=60000)
                html = await page.content()
                await asyncio.sleep(random.uniform(3, 8))
                soup = BeautifulSoup(html, "html.parser")
            except:
                await page.close()
                continue

            result = {
                 'complaint_no': complaint_no,
                 'title': soup.title.get_text(strip=True),
                 'complaint_at': None,
                 'bin':None,
                 'owner':None,
                 'disposition':None,
                 'comments':None
                }
            
            # Complaint at
            tag = soup.find('td',string=re.compile('Complaint at:'))
            if tag:
                result['complaint_at'] = (
            tag.get_text(' ', strip=True)
            .replace('Complaint at:', '')
            .strip()
        )
            #bin
            bin_text = soup.find(string=re.compile('BIN:'))
            if bin_text:
                result['bin'] = (
                    bin_text.parent.get_text(' ', strip=True).replace('BIN:', '').strip()
                )

            #owner
            owner = soup.find(string=re.compile('^Owner:'))
            if owner:
                result['owner'] = (
                    owner.find_next('td').get_text(' ', strip=True)
                )

            #Disposition
            disp = soup.find(string=re.compile('^Disposition:'))
            if disp:
                result['disposition'] = (
                    disp.parent.find_next('td').get_text(' ', strip=True)
                )

            #commnets
            comments = soup.find(string=re.compile('^Comments:'))
            if comments:
                result['comments'] = (
                    comments.parent.find_next('td').get_text(' ', strip=True)
                    )
            results.append(result)

        await browser.close()
        
    df = pd.DataFrame(results)

    return df
 
df = await main()

In [66]:
df.to_csv('complaint_detail.csv', index=False)

### Analyze complaint detail

In [46]:
df['complaint_at'].value_counts()

complaint_at
240 EAST 27 STREET    5
200 EAST 64 STREET    5
425 5 AVENUE          5
445 5 AVENUE          5
622 3 AVENUE          4
                     ..
175 WATER STREET      1
138-35 39 AVENUE      1
501 WEST 52 STREET    1
1825 EMMONS AVENUE    1
1817 EMMONS AVENUE    1
Name: count, Length: 300, dtype: int64

In [48]:
df['disposition'].unique()

<StringArray>
['10/13/2017 - A8 - ECB VIOLATION SERVED',
 '04/10/2023 - A8 - ECB VIOLATION SERVED',
 '02/16/2018 - A8 - ECB VIOLATION SERVED',
                                      nan,
 '12/21/2017 - A8 - ECB VIOLATION SERVED',
 '04/19/2022 - A8 - ECB VIOLATION SERVED',
 '05/23/2018 - A8 - ECB VIOLATION SERVED',
 '03/21/2022 - A8 - ECB VIOLATION SERVED',
 '02/27/2017 - A8 - ECB VIOLATION SERVED',
 '11/28/2017 - A8 - ECB VIOLATION SERVED',
 ...
 '08/22/2023 - A8 - ECB VIOLATION SERVED',
 '05/06/2020 - A8 - ECB VIOLATION SERVED',
 '10/12/2023 - A8 - ECB VIOLATION SERVED',
 '09/20/2023 - A8 - ECB VIOLATION SERVED',
 '01/12/2023 - A8 - ECB VIOLATION SERVED',
 '07/08/2019 - A8 - ECB VIOLATION SERVED',
 '01/17/2023 - A8 - ECB VIOLATION SERVED',
 '12/21/2023 - A8 - ECB VIOLATION SERVED',
 '06/18/2021 - A8 - ECB VIOLATION SERVED',
 '02/20/2025 - A8 - ECB VIOLATION SERVED']
Length: 252, dtype: str

In [54]:
df[['disp_date', 'disp_code', 'disp_result']] = (
    df['disposition'].str.split(' - ', expand=True)
)
df

,complaint_no,title,complaint_at,bin,owner,disposition,comments,disp_date,disp_code,disp_result
0,1462915,Overview for Complaint #:1462915 = RESOLVED,55 WATER STREET,1083346,NEW WATER STREET CORP.,10/13/2017 - A8 - ECB VIOLATION SERVED,PUBLIC PLAZA MISSING ENTRY PLAQUE/SIGN ON THE ...,10/13/2017,A8,ECB VIOLATION SERVED
1,1633608,Overview for Complaint #:1633608 = RESOLVED,55 WATER STREET,1083346,NEW WATER STREET CORP.,04/10/2023 - A8 - ECB VIOLATION SERVED,"ESCALATORS TO ELEVATED POPS PLAZA ARE COVERED,...",04/10/2023,A8,ECB VIOLATION SERVED
2,1472559,Overview for Complaint #:1472559 = RESOLVED,1 PENN PLAZA,1014387,KORPENN LLC,02/16/2018 - A8 - ECB VIOLATION SERVED,"PLAZA NOT PROPERL MAINTAINED , MISSING SEATING...",02/16/2018,A8,ECB VIOLATION SERVED
3,1527139,Visitor Prioritization - NYC Department of Bui...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1468464,Overview for Complaint #:1468464 = RESOLVED,1633 BROADWAY,1024812,PGREF I 1633 BROADWAY TOWER L.,12/21/2017 - A8 - ECB VIOLATION SERVED,"OPEN AIR PLAQUE MISSING ARTWOR,TWO PLAQUE/SIGN...",12/21/2017,A8,ECB VIOLATION SERVED
...,...,...,...,...,...,...,...,...,...,...
579,3A27969,Overview for Complaint #:3A27969 = RESOLVED,1825 EMMONS AVENUE,3247051,UNAVAILABLE OWNER,09/09/2025 - A8 - ECB VIOLATION SERVED,AT TIME OF INSPECTION THE FOLLOWING ITEMS ARE ...,09/09/2025,A8,ECB VIOLATION SERVED
580,3918419,Overview for Complaint #:3918419 = RESOLVED,1809 EMMONS AVENUE,3247051,UNAVAILABLE OWNER,07/28/2023 - A8 - ECB VIOLATION SERVED,OBSERVED PLAZA BEING TAKEN OVER AND OCCUPIED W...,07/28/2023,A8,ECB VIOLATION SERVED
581,3796731,Overview for Complaint #:3796731 = RESOLVED,1817 EMMONS AVENUE,3247051,UNAVAILABLE OWNER,06/18/2021 - A8 - ECB VIOLATION SERVED,DESIGN CHANGES HAVE BEEN MADE TO PLAZA WITH OU...,06/18/2021,A8,ECB VIOLATION SERVED
582,3A01737,Overview for Complaint #:3A01737 = RESOLVED,1809 EMMONS AVENUE,3247051,UNAVAILABLE OWNER,02/20/2025 - A8 - ECB VIOLATION SERVED,OBSERVED FIXED PERMANENT SEATS HAVE BEEN REMOV...,02/20/2025,A8,ECB VIOLATION SERVED
583,3826753,Overview for Complaint #:3826753 = RESOLVED,1809 EMMONS AVENUE,3247051,UNAVAILABLE OWNER,03/01/2022 - A8 - ECB VIOLATION SERVED,AT TIME OF INSPECTION 2 EATING ESTABLISHMENT I...,03/01/2022,A8,ECB VIOLATION SERVED

In [60]:
df['disp_date'] = pd.to_datetime(df['disp_date'])
df['year'] = df['disp_date'].dt.year.astype('Int64')
df['year'].value_counts().sort_index()

year
2000    11
2001    11
2002     2
2007     1
2008     3
2010     4
2012     1
2013     3
2014     1
2015     1
2016     9
2017    66
2018    69
2019    70
2020    24
2021    17
2022    66
2023    39
2024    36
2025    19
2026     7
Name: count, dtype: Int64

In [61]:
df['disp_code'].value_counts()

disp_code
A8    427
A1     23
A9      9
H3      1
Name: count, dtype: int64

In [62]:
df['disp_result'].value_counts()

disp_result
ECB VIOLATION SERVED                                                     427
BUILDINGS VIOLATION(S) SERVED                                             23
ECB & BUILDINGS VIOLATIONS SERVED                                          9
BUILDING VIOLATION ISSUED FOR FAILURE TO OBEY STOP WORK ORDER 1445153      1
Name: count, dtype: int64

In [65]:
df = df.sort_values('disp_date', ascending=False)
df.head(20)

,complaint_no,title,complaint_at,bin,owner,disposition,comments,disp_date,disp_code,disp_result,year
17,1725087,Overview for Complaint #:1725087 = RESOLVED,1251 AVENUE OF THE AMERICAS,1022706,UNAVAILABLE OWNER,06/23/2026 - A8 - ECB VIOLATION SERVED,DOUBLE-KNOT RESTAURANT HAS EXPANDED ONTO THE P...,2026-06-23,A8,ECB VIOLATION SERVED,2026
213,1724719,Overview for Complaint #:1724719 = RESOLVED,301 EAST 79 STREET,1049261,CONTINENTAL TOWERS CONDO,06/03/2026 - A8 - ECB VIOLATION SERVED,POPS SIGNAGE DOESN'T CONFORM TO DCP REGULATION...,2026-06-03,A8,ECB VIOLATION SERVED,2026
349,1725403,Overview for Complaint #:1725403 = RESOLVED,118 EAST 60 STREET,1041902,118 E 60 OWNERS INC,05/18/2026 - A8 - ECB VIOLATION SERVED,POPS SITE REQUIRES SIGNAGE APPROVED BY DCP POS...,2026-05-18,A8,ECB VIOLATION SERVED,2026
398,1724808,Overview for Complaint #:1724808 = RESOLVED,422 EAST 72 STREET,1045832,OXFORD CONDO C/O B H S,05/18/2026 - A8 - ECB VIOLATION SERVED,POPS SIGNAGE IS SUBSTANTIALLY BLOCKED BY PROPE...,2026-05-18,A8,ECB VIOLATION SERVED,2026
71,1725121,Overview for Complaint #:1725121 = RESOLVED,630 1 AVENUE,1022060,ANTHONY PAUL GIORGIO,05/14/2026 - A8 - ECB VIOLATION SERVED,"POPS SITE, FAILURE TO COMPLY WITH DCP REQUIRED...",2026-05-14,A8,ECB VIOLATION SERVED,2026
254,1724921,Overview for Complaint #:1724921 = RESOLVED,475 PARK AVENUE SOUTH,1018471,475 PARK AVENUE SOUTH,05/12/2026 - A8 - ECB VIOLATION SERVED,POS SITE REQUIRES DCP REGULATED SIGNAGE ADVISI...,2026-05-12,A8,ECB VIOLATION SERVED,2026
362,1724410,Overview for Complaint #:1724410 = RESOLVED,560 LEXINGTON AVENUE,1036451,560 LEXCO LLC,05/12/2026 - A8 - ECB VIOLATION SERVED,"AS PER DCP AGENCY RECORDS, 8 MOVABLE CHAIRS AR...",2026-05-12,A8,ECB VIOLATION SERVED,2026
174,1708464,Overview for Complaint #:1708464 = RESOLVED,10 WEST 66 STREET,1028163,10 WEST 66TH STREET CORPORATIO,11/12/2025 - A8 - ECB VIOLATION SERVED,"POPS COMPLIANCE, PLAQUE NOT EVIDENT AT TIME O...",2025-11-12,A8,ECB VIOLATION SERVED,2025
365,1708462,Overview for Complaint #:1708462 = RESOLVED,130 WEST 67 STREET,1028847,TOULAINE OWNERS CORP,11/12/2025 - A8 - ECB VIOLATION SERVED,"AT TIME OF INSPECTION, POPS PLAQUE NOT EVIDENT...",2025-11-12,A8,ECB VIOLATION SERVED,2025
526,1704739,Overview for Complaint #:1704739 = RESOLVED,45 BROADWAY,1000804,45 BROADWAY LLC,10/14/2025 - A8 - ECB VIOLATION SERVED,"AT TIME OF INSPECTION, TRINITY PLACE SIDE ESCA...",2025-10-14,A8,ECB VIOLATION SERVED,2025
42,1704284,Overview for Complaint #:1704284 = RESOLVED,180 MAIDEN LANE,1000874,MAIDEN GLASS LLC,09/15/2025 - A8 - ECB VIOLATION SERVED,AT TIME OF INSPECTION OBSERVED DCP UNAPPROVED ...,2025-09-15,A8,ECB VIOLATION SERVED,2025
126,1703238,Overview for Complaint #:1703238 = RESOLVED,437 MADISON AVENUE,1035455,MADISON AVENUE FEE,09/15/2025 - A8 - ECB VIOLATION SERVED,"AT TIME OF INSPECTION, POPS ON ALL SIDES IS BL...",2025-09-15,A8,ECB VIOLATION SERVED,2025
579,3A27969,Overview for Complaint #:3A27969 = RESOLVED,1825 EMMONS AVENUE,3247051,UNAVAILABLE OWNER,09/09/2025 - A8 - ECB VIOLATION SERVED,AT TIME OF INSPECTION THE FOLLOWING ITEMS ARE ...,2025-09-09,A8,ECB VIOLATION SERVED,2025
50,1702498,Overview for Complaint #:1702498 = RESOLVED,919 3 AVENUE,1038577,SL GREEN REALTY CORP.,09/09/2025 - A8 - ECB VIOLATION SERVED,AT TIME OF INSPECTION POPS SIGNAGE NOT OBSERVE...,2025-09-09,A8,ECB VIOLATION SERVED,2025
424,1702396,Overview for Complaint #:1702396 = RESOLVED,222 EAST 39 STREET,1020361,BLDG LIC 39TH ST LLC,09/03/2025 - A8 - ECB VIOLATION SERVED,"AT TIME OF INSPECTION, DEFECTIVE SIGNAGE, WEAT...",2025-09-03,A8,ECB VIOLATION SERVED,2025
439,3A20463,Overview for Complaint #:3A20463 = RESOLVED,230 ASHLAND PLACE,3393804,UNAVAILABLE OWNER,07/15/2025 - A8 - ECB VIOLATION SERVED,POPS SITE WATER FOUNTAIN ISN'T WORKING AS REQU...,2025-07-15,A8,ECB VIOLATION SERVED,2025
444,1699180,Overview for Complaint #:1699180 = RESOLVED,311 EAST 38 STREET,1021933,NAME NOT ON FILE,07/15/2025 - A8 - ECB VIOLATION SERVED,POPS SITE WATER FOUNTAIN ISN'T WORKING AS REQU...,2025-07-15,A8,ECB VIOLATION SERVED,2025
390,1697455,Overview for Complaint #:1697455 = RESOLVED,200 EAST 89 STREET,1073221,MONARCH CONDO BD/MGRS,06/18/2025 - A8 - ECB VIOLATION SERVED,FAILURE TO MAINTAIN POPS IN COMPLIANCE WITH DC...,2025-06-18,A8,ECB VIOLATION SERVED,2025
389,1697783,Overview for Complaint #:1697783 = RESOLVED,200 EAST 89 STREET,1073221,MONARCH CONDO BD/MGRS,06/18/2025 - A8 - ECB VIOLATION SERVED,FAILURE TO COMPLY WITH DCP SIGNAGE COMPLIANCE....,2025-06-18,A8,ECB VIOLATION SERVED,2025
298,1696053,Overview for Complaint #:1696053 = RESOLVED,44 WEST 62 STREET,1027365,LINCOLN PLAZA TENANTS CORP,06/03/2025 - A8 - ECB VIOLATION SERVED,TEMPORARY ALUMINUM RAMP PARTIALLY OBSTRUCTING ...,2025-06-03,A8,ECB VIOLATION SERVED,2025