## Get POPS data

In [1]:
!pip install --quiet python-dotenv

In [2]:
pip install sodapy

Requirement already satisfied: sodapy in /Users/kunihiro-iwasaki/.venvs/lede/lib/python3.13/site-packages (2.2.0)
Requirement already satisfied: requests>=2.28.1 in /Users/kunihiro-iwasaki/.venvs/lede/lib/python3.13/site-packages (from sodapy) (2.34.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/kunihiro-iwasaki/.venvs/lede/lib/python3.13/site-packages (from requests>=2.28.1->sodapy) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /Users/kunihiro-iwasaki/.venvs/lede/lib/python3.13/site-packages (from requests>=2.28.1->sodapy) (3.17)
Requirement already satisfied: urllib3<3,>=1.26 in /Users/kunihiro-iwasaki/.venvs/lede/lib/python3.13/site-packages (from requests>=2.28.1->sodapy) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in /Users/kunihiro-iwasaki/.venvs/lede/lib/python3.13/site-packages (from requests>=2.28.1->sodapy) (2026.5.20)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import os
import requests
import pandas as pd
from sodapy import Socrata
from dotenv import load_dotenv
load_dotenv()
os.environ["API_KEY_1"][:8] + "..."

'Yrf8cVZZ...'

In [4]:
#Privately Owned Public Spaces API endpoint
#url = 'https://data.cityofnewyork.us/api/v3/views/rvih-nhyn/query.json'
#response = requests.get(url)
#data = response.json()
#df = pd.DataFrame(data)
#df['building_address_with_zip']

In [2]:
# Example authenticated client (needed for non-public datasets):
client = Socrata("data.cityofnewyork.us",
                  os.environ.get("API_KEY_1"),
                  username=os.environ.get("USER_NAME"),
                  password=os.environ.get("PASS")
                )

# First 1000 results, returned as JSON from API / converted to Python list of
# dictionaries by sodapy.
results = client.get("rvih-nhyn", limit=1000)

# Convert to pandas DataFrame
results_df = pd.DataFrame.from_records(results)
results_df

,pops_number,borough_name,borocode,community_district,address_number,street_name,zip_code,building_address_with_zip,tax_block,tax_lot,...,bin,bbl,geocoded_column,:@computed_region_f5dn_yrer,:@computed_region_yeji_bk3q,:@computed_region_92fq_4b7q,:@computed_region_sbqj_enih,:@computed_region_efsh_h5xi,other_required,permitted_amenities
0,M050022,Manhattan,1,5,1350,SIXTH AVENUE,10019,"1350 SIXTH AVENUE, New York, NY 10019",1270,71,...,1034815,1012700071,"{'type': 'Point', 'coordinates': [-73.977778, ...",11,4,51,10,12081,NaN,NaN
1,M050065,Manhattan,1,5,3,PARK AVENUE,10016,"3 PARK AVENUE, New York, NY 10016",889,7501,...,1087537,1008897501,"{'type': 'Point', 'coordinates': [-73.981075, ...",11,4,50,8,12078,NaN,NaN
2,M050117,Manhattan,1,5,415,MADISON AVENUE,10017,"415 MADISON AVENUE, New York, NY 10017",1284,21,...,1000000,1012840021,"{'type': 'Point', 'coordinates': [-73.976058, ...",11,4,51,10,12079,NaN,NaN
3,M080022,Manhattan,1,8,353,EAST 72 STREET,10021,"353 EAST 72 STREET, New York, NY 10021",1447,19,...,1044882,1014470019,"{'type': 'Point', 'coordinates': [-73.956462, ...",23,4,1,11,12083,NaN,NaN
4,M080069,Manhattan,1,8,1675,YORK AVENUE,10128,"1675 YORK AVENUE, New York, NY 10128",1568,21,...,1050621,1015680021,"{'type': 'Point', 'coordinates': [-73.946331, ...",23,4,1,11,10099,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
387,M060016,Manhattan,1,6,240,EAST 38 STREET,10016,"240 EAST 38 STREET, New York, NY 10016",918,7501,...,1020338,1009187501,"{'type': 'Point', 'coordinates': [-73.97495, 4...",71,4,51,9,12078,NaN,NaN
388,M060023,Manhattan,1,6,311,EAST 38 STREET,10016,"311 EAST 38 STREET, New York, NY 10016",944,7501,...,1021933,1009447501,"{'type': 'Point', 'coordinates': [-73.973221, ...",71,4,51,9,12078,2 additional amenities,NaN
389,M080078,Manhattan,1,8,455,EAST 86 STREET,10028,"455 EAST 86 STREET, New York, NY 10028",1566,7501,...,1073878,1015667501,"{'type': 'Point', 'coordinates': [-73.947177, ...",23,4,1,11,12425,NaN,NaN
390,M060033,Manhattan,1,6,900,THIRD AVENUE,10022,"900 THIRD AVENUE, New York, NY 10022",1309,32,...,1081162,1013090032,"{'type': 'Point', 'coordinates': [-73.969094, ...",71,4,51,9,12419,NaN,NaN
391,M050005,Manhattan,1,5,499,PARK AVENUE,10022,"499 PARK AVENUE, New York, NY 10022",1313,4,...,1037164,1013130004,"{'type': 'Point', 'coordinates': [-73.969605, ...",11,4,51,10,12419,NaN,NaN

In [3]:
results_df['building_address_with_zip'].value_counts()

building_address_with_zip
1350 SIXTH AVENUE, New York, NY 10019     1
3 PARK AVENUE, New York, NY 10016         1
415 MADISON AVENUE, New York, NY 10017    1
353 EAST 72 STREET, New York, NY 10021    1
1675 YORK AVENUE, New York, NY 10128      1
                                         ..
240 EAST 38 STREET, New York, NY 10016    1
311 EAST 38 STREET, New York, NY 10016    1
455 EAST 86 STREET, New York, NY 10028    1
900 THIRD AVENUE, New York, NY 10022      1
499 PARK AVENUE, New York, NY 10022       1
Name: count, Length: 392, dtype: int64

In [4]:
results_df['sf'] = (
    results_df['size_required'].str.findall(r'(\d+(?:\.\d+)?)\s*sf')
)
results_df['total_sf'] = results_df['sf'].apply(
    lambda x: sum(float(v) for v in x) if isinstance(x, list) else pd.NA
)
results_df

,pops_number,borough_name,borocode,community_district,address_number,street_name,zip_code,building_address_with_zip,tax_block,tax_lot,...,geocoded_column,:@computed_region_f5dn_yrer,:@computed_region_yeji_bk3q,:@computed_region_92fq_4b7q,:@computed_region_sbqj_enih,:@computed_region_efsh_h5xi,other_required,permitted_amenities,sf,total_sf
0,M050022,Manhattan,1,5,1350,SIXTH AVENUE,10019,"1350 SIXTH AVENUE, New York, NY 10019",1270,71,...,"{'type': 'Point', 'coordinates': [-73.977778, ...",11,4,51,10,12081,NaN,NaN,[5879.50],5879.5
1,M050065,Manhattan,1,5,3,PARK AVENUE,10016,"3 PARK AVENUE, New York, NY 10016",889,7501,...,"{'type': 'Point', 'coordinates': [-73.981075, ...",11,4,50,8,12078,NaN,NaN,"[2761.00, 8862.00]",11623.0
2,M050117,Manhattan,1,5,415,MADISON AVENUE,10017,"415 MADISON AVENUE, New York, NY 10017",1284,21,...,"{'type': 'Point', 'coordinates': [-73.976058, ...",11,4,51,10,12079,NaN,NaN,NaN,<NA>
3,M080022,Manhattan,1,8,353,EAST 72 STREET,10021,"353 EAST 72 STREET, New York, NY 10021",1447,19,...,"{'type': 'Point', 'coordinates': [-73.956462, ...",23,4,1,11,12083,NaN,NaN,"[786.00, 2411.00]",3197.0
4,M080069,Manhattan,1,8,1675,YORK AVENUE,10128,"1675 YORK AVENUE, New York, NY 10128",1568,21,...,"{'type': 'Point', 'coordinates': [-73.946331, ...",23,4,1,11,10099,NaN,NaN,[11754.00],11754.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
387,M060016,Manhattan,1,6,240,EAST 38 STREET,10016,"240 EAST 38 STREET, New York, NY 10016",918,7501,...,"{'type': 'Point', 'coordinates': [-73.97495, 4...",71,4,51,9,12078,NaN,NaN,"[5358.30, 9041.70]",14400.0
388,M060023,Manhattan,1,6,311,EAST 38 STREET,10016,"311 EAST 38 STREET, New York, NY 10016",944,7501,...,"{'type': 'Point', 'coordinates': [-73.973221, ...",71,4,51,9,12078,2 additional amenities,NaN,[3871.17],3871.17
389,M080078,Manhattan,1,8,455,EAST 86 STREET,10028,"455 EAST 86 STREET, New York, NY 10028",1566,7501,...,"{'type': 'Point', 'coordinates': [-73.947177, ...",23,4,1,11,12425,NaN,NaN,[1982.50],1982.5
390,M060033,Manhattan,1,6,900,THIRD AVENUE,10022,"900 THIRD AVENUE, New York, NY 10022",1309,32,...,"{'type': 'Point', 'coordinates': [-73.969094, ...",71,4,51,9,12419,NaN,NaN,[2300.00],2300.0
391,M050005,Manhattan,1,5,499,PARK AVENUE,10022,"499 PARK AVENUE, New York, NY 10022",1313,4,...,"{'type': 'Point', 'coordinates': [-73.969605, ...",11,4,51,10,12419,NaN,NaN,"[1450.00, 525.00, 487.00, 1540.00]",4002.0

In [5]:
results_df.columns.tolist()

['pops_number',
 'borough_name',
 'borocode',
 'community_district',
 'address_number',
 'street_name',
 'zip_code',
 'building_address_with_zip',
 'tax_block',
 'tax_lot',
 'building_name',
 'building_location',
 'year_completed',
 'building_constructed',
 'public_space_type',
 'developer',
 'building_architect',
 'principal_public_space',
 'size_required',
 'hour_of_access_required',
 'amenities_required',
 'physically_disabled',
 'latitude',
 'longitude',
 'xcoordinate',
 'ycoordinate',
 'council_district',
 'census_tract',
 'bin',
 'bbl',
 'geocoded_column',
 ':@computed_region_f5dn_yrer',
 ':@computed_region_yeji_bk3q',
 ':@computed_region_92fq_4b7q',
 ':@computed_region_sbqj_enih',
 ':@computed_region_efsh_h5xi',
 'other_required',
 'permitted_amenities',
 'sf',
 'total_sf']

In [6]:
results_df2 = results_df[['building_name','pops_number','building_address_with_zip',
                          'year_completed','public_space_type','total_sf','size_required',
                          'hour_of_access_required','amenities_required','physically_disabled',
                          'developer','borough_name','latitude','longitude','bin','bbl']]
results_df2 = results_df2.sort_values('total_sf', ascending=False)
results_df2.head()

,building_name,pops_number,building_address_with_zip,year_completed,public_space_type,total_sf,size_required,hour_of_access_required,amenities_required,physically_disabled,developer,borough_name,latitude,longitude,bin,bbl
223,NaN,M010025,"55 WATER STREET, New York, NY 10041",1970,Arcade; Elevated Plaza; Plaza,85046.0,Arcade 10254.00 sf; Elevated Plaza 41485.00 sf...,24 Hours; Closing for Events; Restricted Hours,Escalator; Food Service; Lighting; None; Other...,Full/Partial,Uris 55 Water St. Corp.,Manhattan,40.703183,-74.009154,1083346,1000327501
206,Marriott Marquis,M050091,"1535 BROADWAY, New York, NY 10036",1985,Broadway Plaza; Covered Public Pedestrian Area...,74220.0,Broadway Plaza 4000.00 sf; Covered Public Pede...,24 Hours; Restricted Hours,Climate Control; Elevator; Other Required; Pla...,Full/Partial,Portman Properties,Manhattan,40.758627,-73.986197,1024727,1010177501
134,One Penn Plaza,M050064,"1 PENNSYLVANIA PLAZA, New York, NY 10119",1972,Arcade; Plaza,53917.5,Arcade 3822.00 sf; Plaza 50095.50 sf,24 Hours,Artwork; Bicycle Parking; Drinking Fountain; L...,Full/Partial,Harry Helmsley & Larry Wien,Manhattan,40.751263,-73.992374,1014387,1007830070
336,West End Towers,M070027,"75 WEST END AVENUE, New York, NY 10023",1993,Public Open Spaces,51497.0,Public Open Spaces 51497.00 sf,Restricted Hours,Lighting; Other Required; Planting; Plaque/Sig...,Full/Partial,Brodsky Organization,Manhattan,40.773792,-73.989403,1088686,1011710063
203,Salomon Smith Barney,M010037,"388 GREENWICH STREET, New York, NY 10013",1986,Plaza; Public Plaza,45693.0,Plaza 22906.00 sf; Public Plaza 22787.00 sf,24 Hours,Bicycle Parking; Drinking Fountain; Lighting; ...,Full/Partial,NaN,Manhattan,40.720865,-74.011003,1082816,1002160001

In [7]:
results_df2['address'] = (
    results_df2['building_address_with_zip']
        .astype(str)
        .str.upper()
        .str.replace(r"[\s,]+", '', regex=True)
)
results_df2.head()

,building_name,pops_number,building_address_with_zip,year_completed,public_space_type,total_sf,size_required,hour_of_access_required,amenities_required,physically_disabled,developer,borough_name,latitude,longitude,bin,bbl,address
223,NaN,M010025,"55 WATER STREET, New York, NY 10041",1970,Arcade; Elevated Plaza; Plaza,85046.0,Arcade 10254.00 sf; Elevated Plaza 41485.00 sf...,24 Hours; Closing for Events; Restricted Hours,Escalator; Food Service; Lighting; None; Other...,Full/Partial,Uris 55 Water St. Corp.,Manhattan,40.703183,-74.009154,1083346,1000327501,55WATERSTREETNEWYORKNY10041
206,Marriott Marquis,M050091,"1535 BROADWAY, New York, NY 10036",1985,Broadway Plaza; Covered Public Pedestrian Area...,74220.0,Broadway Plaza 4000.00 sf; Covered Public Pede...,24 Hours; Restricted Hours,Climate Control; Elevator; Other Required; Pla...,Full/Partial,Portman Properties,Manhattan,40.758627,-73.986197,1024727,1010177501,1535BROADWAYNEWYORKNY10036
134,One Penn Plaza,M050064,"1 PENNSYLVANIA PLAZA, New York, NY 10119",1972,Arcade; Plaza,53917.5,Arcade 3822.00 sf; Plaza 50095.50 sf,24 Hours,Artwork; Bicycle Parking; Drinking Fountain; L...,Full/Partial,Harry Helmsley & Larry Wien,Manhattan,40.751263,-73.992374,1014387,1007830070,1PENNSYLVANIAPLAZANEWYORKNY10119
336,West End Towers,M070027,"75 WEST END AVENUE, New York, NY 10023",1993,Public Open Spaces,51497.0,Public Open Spaces 51497.00 sf,Restricted Hours,Lighting; Other Required; Planting; Plaque/Sig...,Full/Partial,Brodsky Organization,Manhattan,40.773792,-73.989403,1088686,1011710063,75WESTENDAVENUENEWYORKNY10023
203,Salomon Smith Barney,M010037,"388 GREENWICH STREET, New York, NY 10013",1986,Plaza; Public Plaza,45693.0,Plaza 22906.00 sf; Public Plaza 22787.00 sf,24 Hours,Bicycle Parking; Drinking Fountain; Lighting; ...,Full/Partial,NaN,Manhattan,40.720865,-74.011003,1082816,1002160001,388GREENWICHSTREETNEWYORKNY10013

In [121]:
results_df2['address_key'] = results_df2['address'].str.replace('NEWYORKNY', '', regex=False)
results_df2.to_csv('POPS.csv', index=False)

## Get DOB_complaint data
### sort by complaint_category=78(Privately Owned Public Space/Non-Compliance)

In [9]:
# Example authenticated client (needed for non-public datasets):
client = Socrata('data.cityofnewyork.us',
                  os.environ.get('API_KEY_2'),
                  username=os.environ.get('USER_NAME'),
                  password=os.environ.get('PASS')
                )

#First 3102000 results, returned as JSON from API / converted to Python list of
#dictionaries by sodapy.
results = client.get(
    "vztk-gaf7",
    where="complaint_category = '78'",
    limit=50000
)

# Convert to pandas DataFrame
results_df3 = pd.DataFrame.from_records(results)
results_df3

,complaint_number,status,date_entered,house_number,zip_code,house_street,bin,community_board,complaint_category,unit,disposition_date,disposition_code,inspection_date,dobrundate,special_district
0,1625626,CLOSED,12/31/2022,230,10281,VESEY STREET,1000060,101,78,SPOPS,01/04/2023,I2,01/03/2023,20260702000000,NaN
1,1440339,CLOSED,12/31/2016,120,10017,PARK AVENUE,1035334,105,78,SPOPS,01/17/2017,I2,01/15/2017,20260702000000,NaN
2,4570905,CLOSED,12/31/2013,114-14,11419,95 AVENUE,4198186,409,78,SPOPS,01/02/2014,I1,01/02/2014,20260702000000,NaN
3,4570909,CLOSED,12/31/2013,114-12,11419,95 AVENUE,4198185,409,78,SPOPS,01/02/2014,I1,01/02/2014,20260702000000,NaN
4,4570761,CLOSED,12/30/2013,114-12,11419,95 AVENUE,4198185,409,78,SPOPS,12/30/2013,H1,12/30/2013,20260702000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3706,4571027,CLOSED,01/02/2014,114-14,11419,95 AVENUE,4198186,409,78,SPOPS,01/02/2014,H1,01/02/2014,20260702000000,NaN
3707,4571171,CLOSED,01/02/2014,95-57,11419,114 STREET,4198232,409,78,SPOPS,01/03/2014,I1,01/03/2014,20260702000000,NaN
3708,4571125,CLOSED,01/02/2014,114-14,11419,95 AVENUE,4198186,409,78,SPOPS,01/03/2014,I1,01/03/2014,20260702000000,NaN
3709,1315535,CLOSED,01/02/2012,100,10038,WILLIAM STREET,1001116,101,78,SPOPS,03/12/2012,I2,03/07/2012,20260702000000,NaN
3710,4570953,CLOSED,01/01/2014,95-29,11419,115 STREET,4198298,409,78,SPOPS,01/02/2014,I1,01/02/2014,20260702000000,NaN

In [10]:
results_df3.columns.tolist()

['complaint_number',
 'status',
 'date_entered',
 'house_number',
 'zip_code',
 'house_street',
 'bin',
 'community_board',
 'complaint_category',
 'unit',
 'disposition_date',
 'disposition_code',
 'inspection_date',
 'dobrundate',
 'special_district']

## merge POPS data and DOB_complaint data(by 'bin')

In [11]:
merged_df = pd.merge(results_df2, results_df3, on='bin', how='inner')
merged_df

,building_name,pops_number,building_address_with_zip,year_completed,public_space_type,total_sf,size_required,hour_of_access_required,amenities_required,physically_disabled,...,zip_code,house_street,community_board,complaint_category,unit,disposition_date,disposition_code,inspection_date,dobrundate,special_district
0,NaN,M010025,"55 WATER STREET, New York, NY 10041",1970,Arcade; Elevated Plaza; Plaza,85046.0,Arcade 10254.00 sf; Elevated Plaza 41485.00 sf...,24 Hours; Closing for Events; Restricted Hours,Escalator; Food Service; Lighting; None; Other...,Full/Partial,...,10041,WATER STREET,101,78,SPOPS,10/13/2017,A8,10/06/2017,20260702000000,NaN
1,NaN,M010025,"55 WATER STREET, New York, NY 10041",1970,Arcade; Elevated Plaza; Plaza,85046.0,Arcade 10254.00 sf; Elevated Plaza 41485.00 sf...,24 Hours; Closing for Events; Restricted Hours,Escalator; Food Service; Lighting; None; Other...,Full/Partial,...,10041,WATER STREET,101,78,SPOPS,01/03/2017,I2,01/03/2017,20260702000000,NaN
2,NaN,M010025,"55 WATER STREET, New York, NY 10041",1970,Arcade; Elevated Plaza; Plaza,85046.0,Arcade 10254.00 sf; Elevated Plaza 41485.00 sf...,24 Hours; Closing for Events; Restricted Hours,Escalator; Food Service; Lighting; None; Other...,Full/Partial,...,10041,WATER STREET,101,78,SPOPS,07/25/2018,I2,07/18/2018,20260702000000,NaN
3,NaN,M010025,"55 WATER STREET, New York, NY 10041",1970,Arcade; Elevated Plaza; Plaza,85046.0,Arcade 10254.00 sf; Elevated Plaza 41485.00 sf...,24 Hours; Closing for Events; Restricted Hours,Escalator; Food Service; Lighting; None; Other...,Full/Partial,...,10041,WATER STREET,101,78,SPOPS,04/10/2023,A8,04/10/2023,20260702000000,NaN
4,NaN,M010025,"55 WATER STREET, New York, NY 10041",1970,Arcade; Elevated Plaza; Plaza,85046.0,Arcade 10254.00 sf; Elevated Plaza 41485.00 sf...,24 Hours; Closing for Events; Restricted Hours,Escalator; Food Service; Lighting; None; Other...,Full/Partial,...,10041,WATER STREET,101,78,SPOPS,04/06/2022,I2,04/04/2022,20260702000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2261,NaN,K150001,"1809 EMMONS AVENUE, Brooklyn, NY 11235",NaN,'Plaza',<NA>,NaN,NaN,NaN,Full/Partial,...,11235,EMMONS AVENUE,315,78,SPOPS,06/18/2021,A8,06/17/2021,20260702000000,NaN
2262,NaN,K150001,"1809 EMMONS AVENUE, Brooklyn, NY 11235",NaN,'Plaza',<NA>,NaN,NaN,NaN,Full/Partial,...,11235,EMMONS AVENUE,315,78,SPOPS,04/22/2022,H1,04/22/2022,20260702000000,NaN
2263,NaN,K150001,"1809 EMMONS AVENUE, Brooklyn, NY 11235",NaN,'Plaza',<NA>,NaN,NaN,NaN,Full/Partial,...,11235,EMMONS AVENUE,315,78,QAU,02/20/2025,A8,02/19/2025,20260702000000,NaN
2264,NaN,K150001,"1809 EMMONS AVENUE, Brooklyn, NY 11235",NaN,'Plaza',<NA>,NaN,NaN,NaN,Full/Partial,...,11235,EMMONS AVENUE,315,78,SPOPS,03/01/2022,A8,03/01/2022,20260702000000,NaN
2265,NaN,M050115,"1241 BROADWAY, New York, NY 10001",NaN,Arcade,<NA>,NaN,NaN,NaN,Full/Partial,...,10001,BROADWAY,105,78,SPOPS,12/16/2022,I2,12/15/2022,20260702000000,NaN

In [12]:
merged_df['disposition_code'].value_counts()

disposition_code
I2    1066
A8     540
I3     261
H1     199
I1      74
A1      30
B1      24
G5      17
A9      13
F5       6
F3       5
F6       4
G2       3
L2       2
B2       1
J6       1
D5       1
F2       1
H3       1
L1       1
C2       1
Name: count, dtype: int64

##### I2=No Violation Warranted for Complaint at Time of Inspection
##### A8=OATH Violation Served★
##### I3=Compliance Inspection Performed
##### H1=Please See Complaint Number
##### A1=Buildings Violation(s) Served★
##### B1=Buildings Violation(s) Prepared and Attempt to Serve will be Made
##### G5=Complaint Referred to New York Police Department (NYPD)
##### A9=OATH and DOB Violations Served★
##### F5=Complaint Referred to Department of Sanitation (DOS)
##### F3=Complaint Referred to NYC Department of Health and Mental Hygiene (DOHMH)
##### F6=Complaint Referred to Department of Transportation (DOT)
##### G2=Complaint Referred to Department of Parks and Recreation (DPR)
##### L2=Stop Work Order Fully Rescinded
##### B2=OATH Summons Prepared and Attempt to Serve will be Made
##### J6=Sign Moratorium 2019
##### D5=Complaint Assigned to Emergency Response Team
##### F2=Complaint Referred to NYS Division of Housing and Community Renewal (DHCR)
##### H3=Building Violation Issued for Failure to Obey Stop Work Order★
##### L1=Partial Stop Work Order
##### C2=Inspector Unable to Gain Access – 2nd Final Attempt

In [13]:
merged_df.columns.tolist()

['building_name',
 'pops_number',
 'building_address_with_zip',
 'year_completed',
 'public_space_type',
 'total_sf',
 'size_required',
 'hour_of_access_required',
 'amenities_required',
 'physically_disabled',
 'developer',
 'borough_name',
 'latitude',
 'longitude',
 'bin',
 'bbl',
 'address',
 'address_key',
 'complaint_number',
 'status',
 'date_entered',
 'house_number',
 'zip_code',
 'house_street',
 'community_board',
 'complaint_category',
 'unit',
 'disposition_date',
 'disposition_code',
 'inspection_date',
 'dobrundate',
 'special_district']

In [92]:
merged_df['bin'].unique()

<StringArray>
['1083346', '1024727', '1014387', '1088686', '1082816', '1000005', '1024812',
 '1043921', '1025450', '1079043',
 ...
 '1090299', '5164632', '1090263', '1089237', '1089695', '1090548', '1090647',
 '1077835', '3247051', '1090786']
Length: 379, dtype: str

### Focus on violations

In [134]:
target_code = ['A8', 'A1', 'A9', 'H3']
filtered_merged_df = merged_df[merged_df['disposition_code'].isin(target_code)]
filtered_merged_df

,building_name,pops_number,building_address_with_zip,year_completed,public_space_type,total_sf,size_required,hour_of_access_required,amenities_required,physically_disabled,...,zip_code,house_street,community_board,complaint_category,unit,disposition_date,disposition_code,inspection_date,dobrundate,special_district
0,NaN,M010025,"55 WATER STREET, New York, NY 10041",1970,Arcade; Elevated Plaza; Plaza,85046.0,Arcade 10254.00 sf; Elevated Plaza 41485.00 sf...,24 Hours; Closing for Events; Restricted Hours,Escalator; Food Service; Lighting; None; Other...,Full/Partial,...,10041,WATER STREET,101,78,SPOPS,10/13/2017,A8,10/06/2017,20260702000000,NaN
3,NaN,M010025,"55 WATER STREET, New York, NY 10041",1970,Arcade; Elevated Plaza; Plaza,85046.0,Arcade 10254.00 sf; Elevated Plaza 41485.00 sf...,24 Hours; Closing for Events; Restricted Hours,Escalator; Food Service; Lighting; None; Other...,Full/Partial,...,10041,WATER STREET,101,78,SPOPS,04/10/2023,A8,04/10/2023,20260702000000,NaN
18,One Penn Plaza,M050064,"1 PENNSYLVANIA PLAZA, New York, NY 10119",1972,Arcade; Plaza,53917.5,Arcade 3822.00 sf; Plaza 50095.50 sf,24 Hours,Artwork; Bicycle Parking; Drinking Fountain; L...,Full/Partial,...,10119,PENN PLAZA,105,78,SPOPS,02/16/2018,A8,12/28/2017,20260702000000,NaN
27,Salomon Smith Barney,M010037,"388 GREENWICH STREET, New York, NY 10013",1986,Plaza; Public Plaza,45693.0,Plaza 22906.00 sf; Public Plaza 22787.00 sf,24 Hours,Bicycle Parking; Drinking Fountain; Lighting; ...,Full/Partial,...,10013,GREENWICH STREET,101,78,SPOPS,11/20/2019,A8,11/08/2019,20260702000000,NaN
41,Paramount Plaza,M050038,"1633 BROADWAY, New York, NY 10019",1971,Special Permit Arcade; Special Permit Plaza; U...,38119.2,Special Permit Arcade 8033.20 sf; Special Perm...,24 Hours,Bicycle Parking; Lighting; Litter Receptacles;...,Full/Partial,...,10019,BROADWAY,105,78,SPOPS,12/21/2017,A8,12/01/2017,20260702000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2255,NaN,K150001,"1809 EMMONS AVENUE, Brooklyn, NY 11235",NaN,'Plaza',<NA>,NaN,NaN,NaN,Full/Partial,...,11235,EMMONS AVENUE,315,78,QAU,09/09/2025,A8,09/09/2025,20260702000000,NaN
2259,NaN,K150001,"1809 EMMONS AVENUE, Brooklyn, NY 11235",NaN,'Plaza',<NA>,NaN,NaN,NaN,Full/Partial,...,11235,EMMONS AVENUE,315,78,SPOPS,07/28/2023,A8,07/26/2023,20260702000000,NaN
2261,NaN,K150001,"1809 EMMONS AVENUE, Brooklyn, NY 11235",NaN,'Plaza',<NA>,NaN,NaN,NaN,Full/Partial,...,11235,EMMONS AVENUE,315,78,SPOPS,06/18/2021,A8,06/17/2021,20260702000000,NaN
2263,NaN,K150001,"1809 EMMONS AVENUE, Brooklyn, NY 11235",NaN,'Plaza',<NA>,NaN,NaN,NaN,Full/Partial,...,11235,EMMONS AVENUE,315,78,QAU,02/20/2025,A8,02/19/2025,20260702000000,NaN
2264,NaN,K150001,"1809 EMMONS AVENUE, Brooklyn, NY 11235",NaN,'Plaza',<NA>,NaN,NaN,NaN,Full/Partial,...,11235,EMMONS AVENUE,315,78,SPOPS,03/01/2022,A8,03/01/2022,20260702000000,NaN

### Number of Buildings in Violation

In [46]:
len(filtered_merged_df['bin'].unique())

280

### disposition date

In [60]:
filtered_merged_df['disposition_date'] = pd.to_datetime(filtered_merged_df['disposition_date'])
filtered_merged_df.sort_values('disposition_date')['disposition_date'].tolist()

[Timestamp('2000-11-14 00:00:00'),
 Timestamp('2000-11-20 00:00:00'),
 Timestamp('2000-11-20 00:00:00'),
 Timestamp('2000-11-20 00:00:00'),
 Timestamp('2000-11-20 00:00:00'),
 Timestamp('2000-11-20 00:00:00'),
 Timestamp('2000-11-20 00:00:00'),
 Timestamp('2000-11-20 00:00:00'),
 Timestamp('2000-11-28 00:00:00'),
 Timestamp('2000-11-28 00:00:00'),
 Timestamp('2000-11-28 00:00:00'),
 Timestamp('2000-11-28 00:00:00'),
 Timestamp('2000-12-04 00:00:00'),
 Timestamp('2001-02-06 00:00:00'),
 Timestamp('2001-02-26 00:00:00'),
 Timestamp('2001-04-10 00:00:00'),
 Timestamp('2001-05-30 00:00:00'),
 Timestamp('2001-05-30 00:00:00'),
 Timestamp('2001-05-31 00:00:00'),
 Timestamp('2001-05-31 00:00:00'),
 Timestamp('2001-07-03 00:00:00'),
 Timestamp('2001-09-10 00:00:00'),
 Timestamp('2001-10-04 00:00:00'),
 Timestamp('2001-10-04 00:00:00'),
 Timestamp('2001-10-04 00:00:00'),
 Timestamp('2001-10-04 00:00:00'),
 Timestamp('2001-10-04 00:00:00'),
 Timestamp('2001-10-04 00:00:00'),
 Timestamp('2002-01-17 00:00:00'),
 Timestamp('2002-02-22 00:00:00'),
 Timestamp('2002-03-11 00:00:00'),
 Timestamp('2002-03-11 00:00:00'),
 Timestamp('2002-08-08 00:00:00'),
 Timestamp('2007-02-21 00:00:00'),
 Timestamp('2007-09-20 00:00:00'),
 Timestamp('2008-02-08 00:00:00'),
 Timestamp('2008-06-17 00:00:00'),
 Timestamp('2008-11-25 00:00:00'),
 Timestamp('2009-02-09 00:00:00'),
 Timestamp('2009-09-14 00:00:00'),
 Timestamp('2010-04-05 00:00:00'),
 Timestamp('2010-08-20 00:00:00'),
 Timestamp('2010-09-09 00:00:00'),
 Timestamp('2010-09-13 00:00:00'),
 Timestamp('2010-09-30 00:00:00'),
 Timestamp('2011-07-21 00:00:00'),
 Timestamp('2012-11-27 00:00:00'),
 Timestamp('2013-05-09 00:00:00'),
 Timestamp('2013-06-03 00:00:00'),
 Timestamp('2013-07-12 00:00:00'),
 Timestamp('2013-07-25 00:00:00'),
 Timestamp('2013-11-19 00:00:00'),
 Timestamp('2014-06-05 00:00:00'),
 Timestamp('2015-11-12 00:00:00'),
 Timestamp('2016-03-07 00:00:00'),
 Timestamp('2016-03-31 00:00:00'),
 Timestamp('2016-04-15 00:00:00'),
 Timestamp('2016-04-15 00:00:00'),
 Timestamp('2016-04-21 00:00:00'),
 Timestamp('2016-06-22 00:00:00'),
 Timestamp('2016-11-07 00:00:00'),
 Timestamp('2016-11-10 00:00:00'),
 Timestamp('2016-11-18 00:00:00'),
 Timestamp('2016-12-20 00:00:00'),
 Timestamp('2017-02-27 00:00:00'),
 Timestamp('2017-03-22 00:00:00'),
 Timestamp('2017-04-03 00:00:00'),
 Timestamp('2017-04-04 00:00:00'),
 Timestamp('2017-05-12 00:00:00'),
 Timestamp('2017-05-12 00:00:00'),
 Timestamp('2017-05-12 00:00:00'),
 Timestamp('2017-05-12 00:00:00'),
 Timestamp('2017-05-15 00:00:00'),
 Timestamp('2017-05-19 00:00:00'),
 Timestamp('2017-06-06 00:00:00'),
 Timestamp('2017-06-08 00:00:00'),
 Timestamp('2017-06-15 00:00:00'),
 Timestamp('2017-06-16 00:00:00'),
 Timestamp('2017-06-29 00:00:00'),
 Timestamp('2017-08-02 00:00:00'),
 Timestamp('2017-08-10 00:00:00'),
 Timestamp('2017-09-11 00:00:00'),
 Timestamp('2017-09-12 00:00:00'),
 Timestamp('2017-09-14 00:00:00'),
 Timestamp('2017-09-14 00:00:00'),
 Timestamp('2017-09-14 00:00:00'),
 Timestamp('2017-09-14 00:00:00'),
 Timestamp('2017-09-14 00:00:00'),
 Timestamp('2017-09-14 00:00:00'),
 Timestamp('2017-09-28 00:00:00'),
 Timestamp('2017-09-28 00:00:00'),
 Timestamp('2017-09-28 00:00:00'),
 Timestamp('2017-09-28 00:00:00'),
 Timestamp('2017-09-28 00:00:00'),
 Timestamp('2017-09-28 00:00:00'),
 Timestamp('2017-10-13 00:00:00'),
 Timestamp('2017-10-13 00:00:00'),
 Timestamp('2017-10-13 00:00:00'),
 Timestamp('2017-10-13 00:00:00'),
 Timestamp('2017-10-13 00:00:00'),
 Timestamp('2017-10-13 00:00:00'),
 Timestamp('2017-10-13 00:00:00'),
 Timestamp('2017-10-13 00:00:00'),
 Timestamp('2017-10-20 00:00:00'),
 Timestamp('2017-10-20 00:00:00'),
 Timestamp('2017-10-20 00:00:00'),
 Timestamp('2017-10-20 00:00:00'),
 Timestamp('2017-10-31 00:00:00'),
 Timestamp('2017-10-31 00:00:00'),
 Timestamp('2017-10-31 00:00:00'),
 Timestamp('2017-10-31 00:00:00'),
 Timestamp('2017-11-13 00:00:00'),
 Timestamp('2017-11-13 00:00:00'),
 Timestamp('2017-11-13 00:00:00'),
 Timestamp('2017-11-13 00:00:00'),
 Timestamp('2017-11-13 00:00:00'),
 Timestamp('2017-11-16 00:00:00'),
 Timestamp('2017-11-17 00:00:00'),
 Timestamp('2017-11-17 00:00:00'),
 Timestamp('2017-11-17 00:00:00'),
 Timestamp('2017-11-22 00:00:00'),
 Timestamp('2017-11-28 00:00:00'),
 Timestamp('2017-11-28 00:00:00'),
 Timestamp('2017-11-28 00:00:00'),
 Timestamp('2017-11-28 00:00:00'),
 Timestamp('2017-12-05 00:00:00'),
 Timestamp('2017-12-05 00:00:00'),
 Timestamp('2017-12-05 00:00:00'),
 Timestamp('2017-12-05 00:00:00'),
 Timestamp('2017-12-05 00:00:00'),
 Timestamp('2017-12-05 00:00:00'),
 Timestamp('2017-12-05 00:00:00'),
 Timestamp('2017-12-05 00:00:00'),
 Timestamp('2017-12-21 00:00:00'),
 Timestamp('2017-12-21 00:00:00'),
 Timestamp('2017-12-21 00:00:00'),
 Timestamp('2017-12-21 00:00:00'),
 Timestamp('2017-12-21 00:00:00'),
 Timestamp('2017-12-21 00:00:00'),
 Timestamp('2017-12-29 00:00:00'),
 Timestamp('2017-12-29 00:00:00'),
 Timestamp('2017-12-29 00:00:00'),
 Timestamp('2017-12-29 00:00:00'),
 Timestamp('2017-12-29 00:00:00'),
 Timestamp('2017-12-29 00:00:00'),
 Timestamp('2017-12-29 00:00:00'),
 Timestamp('2018-01-11 00:00:00'),
 Timestamp('2018-01-22 00:00:00'),
 Timestamp('2018-01-22 00:00:00'),
 Timestamp('2018-01-22 00:00:00'),
 Timestamp('2018-01-22 00:00:00'),
 Timestamp('2018-01-22 00:00:00'),
 Timestamp('2018-01-22 00:00:00'),
 Timestamp('2018-01-22 00:00:00'),
 Timestamp('2018-01-22 00:00:00'),
 Timestamp('2018-01-22 00:00:00'),
 Timestamp('2018-01-22 00:00:00'),
 Timestamp('2018-02-01 00:00:00'),
 Timestamp('2018-02-15 00:00:00'),
 Timestamp('2018-02-15 00:00:00'),
 Timestamp('2018-02-15 00:00:00'),
 Timestamp('2018-02-15 00:00:00'),
 Timestamp('2018-02-15 00:00:00'),
 Timestamp('2018-02-15 00:00:00'),
 Timestamp('2018-02-15 00:00:00'),
 Timestamp('2018-02-15 00:00:00'),
 Timestamp('2018-02-15 00:00:00'),
 Timestamp('2018-02-16 00:00:00'),
 Timestamp('2018-02-16 00:00:00'),
 Timestamp('2018-02-16 00:00:00'),
 Timestamp('2018-03-23 00:00:00'),
 Timestamp('2018-05-21 00:00:00'),
 Timestamp('2018-05-22 00:00:00'),
 Timestamp('2018-05-23 00:00:00'),
 Timestamp('2018-05-23 00:00:00'),
 Timestamp('2018-05-23 00:00:00'),
 Timestamp('2018-05-31 00:00:00'),
 Timestamp('2018-06-11 00:00:00'),
 Timestamp('2018-06-12 00:00:00'),
 Timestamp('2018-06-16 00:00:00'),
 Timestamp('2018-06-16 00:00:00'),
 Timestamp('2018-06-16 00:00:00'),
 Timestamp('2018-06-16 00:00:00'),
 Timestamp('2018-06-16 00:00:00'),
 Timestamp('2018-06-16 00:00:00'),
 Timestamp('2018-06-16 00:00:00'),
 Timestamp('2018-06-16 00:00:00'),
 Timestamp('2018-06-16 00:00:00'),
 Timestamp('2018-06-17 00:00:00'),
 Timestamp('2018-06-19 00:00:00'),
 Timestamp('2018-07-03 00:00:00'),
 Timestamp('2018-07-13 00:00:00'),
 Timestamp('2018-07-13 00:00:00'),
 Timestamp('2018-07-13 00:00:00'),
 Timestamp('2018-07-13 00:00:00'),
 Timestamp('2018-07-13 00:00:00'),
 Timestamp('2018-07-13 00:00:00'),
 Timestamp('2018-07-13 00:00:00'),
 Timestamp('2018-07-13 00:00:00'),
 Timestamp('2018-07-16 00:00:00'),
 Timestamp('2018-07-23 00:00:00'),
 Timestamp('2018-07-23 00:00:00'),
 Timestamp('2018-07-31 00:00:00'),
 Timestamp('2018-07-31 00:00:00'),
 Timestamp('2018-07-31 00:00:00'),
 Timestamp('2018-07-31 00:00:00'),
 Timestamp('2018-07-31 00:00:00'),
 Timestamp('2018-07-31 00:00:00'),
 Timestamp('2018-08-07 00:00:00'),
 Timestamp('2018-08-07 00:00:00'),
 Timestamp('2018-08-07 00:00:00'),
 Timestamp('2018-08-07 00:00:00'),
 Timestamp('2018-08-07 00:00:00'),
 Timestamp('2018-08-13 00:00:00'),
 Timestamp('2018-08-21 00:00:00'),
 Timestamp('2018-08-21 00:00:00'),
 Timestamp('2018-08-21 00:00:00'),
 Timestamp('2018-08-21 00:00:00'),
 Timestamp('2018-08-21 00:00:00'),
 Timestamp('2018-09-19 00:00:00'),
 Timestamp('2018-09-19 00:00:00'),
 Timestamp('2018-09-19 00:00:00'),
 Timestamp('2018-09-19 00:00:00'),
 Timestamp('2018-09-19 00:00:00'),
 Timestamp('2018-10-05 00:00:00'),
 Timestamp('2018-10-05 00:00:00'),
 Timestamp('2018-11-08 00:00:00'),
 Timestamp('2018-12-04 00:00:00'),
 Timestamp('2018-12-27 00:00:00'),
 Timestamp('2019-03-14 00:00:00'),
 Timestamp('2019-05-24 00:00:00'),
 Timestamp('2019-05-29 00:00:00'),
 Timestamp('2019-05-29 00:00:00'),
 Timestamp('2019-05-29 00:00:00'),
 Timestamp('2019-05-29 00:00:00'),
 Timestamp('2019-06-03 00:00:00'),
 Timestamp('2019-06-03 00:00:00'),
 Timestamp('2019-06-03 00:00:00'),
 Timestamp('2019-06-03 00:00:00'),
 Timestamp('2019-06-03 00:00:00'),
 Timestamp('2019-06-04 00:00:00'),
 Timestamp('2019-06-06 00:00:00'),
 Timestamp('2019-06-06 00:00:00'),
 Timestamp('2019-06-06 00:00:00'),
 Timestamp('2019-06-07 00:00:00'),
 Timestamp('2019-06-07 00:00:00'),
 Timestamp('2019-06-10 00:00:00'),
 Timestamp('2019-06-10 00:00:00'),
 Timestamp('2019-06-10 00:00:00'),
 Timestamp('2019-06-10 00:00:00'),
 Timestamp('2019-06-11 00:00:00'),
 Timestamp('2019-06-11 00:00:00'),
 Timestamp('2019-06-14 00:00:00'),
 Timestamp('2019-06-14 00:00:00'),
 Timestamp('2019-06-14 00:00:00'),
 Timestamp('2019-06-14 00:00:00'),
 Timestamp('2019-06-14 00:00:00'),
 Timestamp('2019-06-17 00:00:00'),
 Timestamp('2019-06-17 00:00:00'),
 Timestamp('2019-06-17 00:00:00'),
 Timestamp('2019-06-17 00:00:00'),
 Timestamp('2019-06-17 00:00:00'),
 Timestamp('2019-06-17 00:00:00'),
 Timestamp('2019-06-17 00:00:00'),
 Timestamp('2019-06-18 00:00:00'),
 Timestamp('2019-06-18 00:00:00'),
 Timestamp('2019-06-18 00:00:00'),
 Timestamp('2019-06-18 00:00:00'),
 Timestamp('2019-06-18 00:00:00'),
 Timestamp('2019-06-18 00:00:00'),
 Timestamp('2019-06-18 00:00:00'),
 Timestamp('2019-06-24 00:00:00'),
 Timestamp('2019-06-24 00:00:00'),
 Timestamp('2019-06-27 00:00:00'),
 Timestamp('2019-06-27 00:00:00'),
 Timestamp('2019-06-27 00:00:00'),
 Timestamp('2019-06-27 00:00:00'),
 Timestamp('2019-06-27 00:00:00'),
 Timestamp('2019-06-27 00:00:00'),
 Timestamp('2019-06-28 00:00:00'),
 Timestamp('2019-06-28 00:00:00'),
 Timestamp('2019-06-28 00:00:00'),
 Timestamp('2019-07-01 00:00:00'),
 Timestamp('2019-07-01 00:00:00'),
 Timestamp('2019-07-01 00:00:00'),
 Timestamp('2019-07-01 00:00:00'),
 Timestamp('2019-07-02 00:00:00'),
 Timestamp('2019-07-02 00:00:00'),
 Timestamp('2019-07-02 00:00:00'),
 Timestamp('2019-07-02 00:00:00'),
 Timestamp('2019-07-02 00:00:00'),
 Timestamp('2019-07-02 00:00:00'),
 Timestamp('2019-07-02 00:00:00'),
 Timestamp('2019-07-02 00:00:00'),
 Timestamp('2019-07-02 00:00:00'),
 Timestamp('2019-07-02 00:00:00'),
 Timestamp('2019-07-02 00:00:00'),
 Timestamp('2019-07-02 00:00:00'),
 Timestamp('2019-07-02 00:00:00'),
 Timestamp('2019-07-02 00:00:00'),
 Timestamp('2019-07-02 00:00:00'),
 Timestamp('2019-07-02 00:00:00'),
 Timestamp('2019-07-08 00:00:00'),
 Timestamp('2019-07-08 00:00:00'),
 Timestamp('2019-09-05 00:00:00'),
 Timestamp('2019-09-12 00:00:00'),
 Timestamp('2019-09-12 00:00:00'),
 Timestamp('2019-09-19 00:00:00'),
 Timestamp('2019-09-19 00:00:00'),
 Timestamp('2019-09-19 00:00:00'),
 Timestamp('2019-09-26 00:00:00'),
 Timestamp('2019-10-16 00:00:00'),
 Timestamp('2019-10-24 00:00:00'),
 Timestamp('2019-10-24 00:00:00'),
 Timestamp('2019-10-24 00:00:00'),
 Timestamp('2019-10-29 00:00:00'),
 Timestamp('2019-10-30 00:00:00'),
 Timestamp('2019-11-13 00:00:00'),
 Timestamp('2019-11-14 00:00:00'),
 Timestamp('2019-11-20 00:00:00'),
 Timestamp('2019-12-04 00:00:00'),
 Timestamp('2019-12-04 00:00:00'),
 Timestamp('2020-01-10 00:00:00'),
 Timestamp('2020-01-15 00:00:00'),
 Timestamp('2020-01-15 00:00:00'),
 Timestamp('2020-01-15 00:00:00'),
 Timestamp('2020-01-22 00:00:00'),
 Timestamp('2020-01-29 00:00:00'),
 Timestamp('2020-01-30 00:00:00'),
 Timestamp('2020-01-30 00:00:00'),
 Timestamp('2020-02-06 00:00:00'),
 Timestamp('2020-05-06 00:00:00'),
 Timestamp('2020-05-28 00:00:00'),
 Timestamp('2020-05-29 00:00:00'),
 Timestamp('2020-06-22 00:00:00'),
 Timestamp('2020-06-29 00:00:00'),
 Timestamp('2020-08-13 00:00:00'),
 Timestamp('2020-08-13 00:00:00'),
 Timestamp('2020-08-24 00:00:00'),
 Timestamp('2020-08-25 00:00:00'),
 Timestamp('2020-09-16 00:00:00'),
 Timestamp('2020-09-22 00:00:00'),
 Timestamp('2020-10-01 00:00:00'),
 Timestamp('2020-10-01 00:00:00'),
 Timestamp('2020-10-05 00:00:00'),
 Timestamp('2020-10-15 00:00:00'),
 Timestamp('2020-10-22 00:00:00'),
 Timestamp('2020-11-13 00:00:00'),
 Timestamp('2020-11-13 00:00:00'),
 Timestamp('2020-12-04 00:00:00'),
 Timestamp('2020-12-21 00:00:00'),
 Timestamp('2020-12-23 00:00:00'),
 Timestamp('2021-02-10 00:00:00'),
 Timestamp('2021-04-16 00:00:00'),
 Timestamp('2021-05-06 00:00:00'),
 Timestamp('2021-05-12 00:00:00'),
 Timestamp('2021-05-12 00:00:00'),
 Timestamp('2021-05-17 00:00:00'),
 Timestamp('2021-05-19 00:00:00'),
 Timestamp('2021-05-19 00:00:00'),
 Timestamp('2021-05-19 00:00:00'),
 Timestamp('2021-05-27 00:00:00'),
 Timestamp('2021-06-11 00:00:00'),
 Timestamp('2021-06-18 00:00:00'),
 Timestamp('2021-06-28 00:00:00'),
 Timestamp('2021-06-28 00:00:00'),
 Timestamp('2021-07-28 00:00:00'),
 Timestamp('2021-07-28 00:00:00'),
 Timestamp('2021-09-07 00:00:00'),
 Timestamp('2021-09-07 00:00:00'),
 Timestamp('2021-09-16 00:00:00'),
 Timestamp('2021-12-08 00:00:00'),
 Timestamp('2021-12-28 00:00:00'),
 Timestamp('2021-12-29 00:00:00'),
 Timestamp('2022-01-07 00:00:00'),
 Timestamp('2022-01-21 00:00:00'),
 Timestamp('2022-01-21 00:00:00'),
 Timestamp('2022-01-25 00:00:00'),
 Timestamp('2022-02-02 00:00:00'),
 Timestamp('2022-02-02 00:00:00'),
 Timestamp('2022-02-08 00:00:00'),
 Timestamp('2022-02-08 00:00:00'),
 Timestamp('2022-02-08 00:00:00'),
 Timestamp('2022-02-22 00:00:00'),
 Timestamp('2022-02-23 00:00:00'),
 Timestamp('2022-03-01 00:00:00'),
 Timestamp('2022-03-01 00:00:00'),
 Timestamp('2022-03-11 00:00:00'),
 Timestamp('2022-03-15 00:00:00'),
 Timestamp('2022-03-15 00:00:00'),
 Timestamp('2022-03-15 00:00:00'),
 Timestamp('2022-03-16 00:00:00'),
 Timestamp('2022-03-16 00:00:00'),
 Timestamp('2022-03-18 00:00:00'),
 Timestamp('2022-03-18 00:00:00'),
 Timestamp('2022-03-18 00:00:00'),
 Timestamp('2022-03-18 00:00:00'),
 Timestamp('2022-03-21 00:00:00'),
 Timestamp('2022-03-21 00:00:00'),
 Timestamp('2022-03-21 00:00:00'),
 Timestamp('2022-03-25 00:00:00'),
 Timestamp('2022-03-25 00:00:00'),
 Timestamp('2022-03-25 00:00:00'),
 Timestamp('2022-03-30 00:00:00'),
 Timestamp('2022-03-30 00:00:00'),
 Timestamp('2022-03-30 00:00:00'),
 Timestamp('2022-04-01 00:00:00'),
 Timestamp('2022-04-01 00:00:00'),
 Timestamp('2022-04-01 00:00:00'),
 Timestamp('2022-04-06 00:00:00'),
 Timestamp('2022-04-06 00:00:00'),
 Timestamp('2022-04-07 00:00:00'),
 Timestamp('2022-04-11 00:00:00'),
 Timestamp('2022-04-11 00:00:00'),
 Timestamp('2022-04-13 00:00:00'),
 Timestamp('2022-04-13 00:00:00'),
 Timestamp('2022-04-15 00:00:00'),
 Timestamp('2022-04-15 00:00:00'),
 Timestamp('2022-04-15 00:00:00'),
 Timestamp('2022-04-15 00:00:00'),
 Timestamp('2022-04-19 00:00:00'),
 Timestamp('2022-04-19 00:00:00'),
 Timestamp('2022-04-19 00:00:00'),
 Timestamp('2022-04-25 00:00:00'),
 Timestamp('2022-04-25 00:00:00'),
 Timestamp('2022-04-27 00:00:00'),
 Timestamp('2022-04-28 00:00:00'),
 Timestamp('2022-04-28 00:00:00'),
 Timestamp('2022-05-03 00:00:00'),
 Timestamp('2022-05-17 00:00:00'),
 Timestamp('2022-05-17 00:00:00'),
 Timestamp('2022-05-17 00:00:00'),
 Timestamp('2022-05-17 00:00:00'),
 Timestamp('2022-05-18 00:00:00'),
 Timestamp('2022-05-18 00:00:00'),
 Timestamp('2022-05-19 00:00:00'),
 Timestamp('2022-05-19 00:00:00'),
 Timestamp('2022-05-19 00:00:00'),
 Timestamp('2022-05-19 00:00:00'),
 Timestamp('2022-05-20 00:00:00'),
 Timestamp('2022-05-20 00:00:00'),
 Timestamp('2022-05-20 00:00:00'),
 Timestamp('2022-05-25 00:00:00'),
 Timestamp('2022-05-25 00:00:00'),
 Timestamp('2022-06-01 00:00:00'),
 Timestamp('2022-06-01 00:00:00'),
 Timestamp('2022-06-01 00:00:00'),
 Timestamp('2022-07-08 00:00:00'),
 Timestamp('2022-07-12 00:00:00'),
 Timestamp('2022-07-27 00:00:00'),
 Timestamp('2022-08-23 00:00:00'),
 Timestamp('2022-10-19 00:00:00'),
 Timestamp('2022-11-03 00:00:00'),
 Timestamp('2022-11-04 00:00:00'),
 Timestamp('2023-01-12 00:00:00'),
 Timestamp('2023-01-12 00:00:00'),
 Timestamp('2023-01-17 00:00:00'),
 Timestamp('2023-01-26 00:00:00'),
 Timestamp('2023-02-02 00:00:00'),
 Timestamp('2023-02-10 00:00:00'),
 Timestamp('2023-02-14 00:00:00'),
 Timestamp('2023-02-27 00:00:00'),
 Timestamp('2023-03-03 00:00:00'),
 Timestamp('2023-03-03 00:00:00'),
 Timestamp('2023-03-03 00:00:00'),
 Timestamp('2023-03-09 00:00:00'),
 Timestamp('2023-03-09 00:00:00'),
 Timestamp('2023-03-28 00:00:00'),
 Timestamp('2023-03-29 00:00:00'),
 Timestamp('2023-04-10 00:00:00'),
 Timestamp('2023-05-09 00:00:00'),
 Timestamp('2023-05-31 00:00:00'),
 Timestamp('2023-07-03 00:00:00'),
 Timestamp('2023-07-05 00:00:00'),
 Timestamp('2023-07-18 00:00:00'),
 Timestamp('2023-07-18 00:00:00'),
 Timestamp('2023-07-18 00:00:00'),
 Timestamp('2023-07-18 00:00:00'),
 Timestamp('2023-07-24 00:00:00'),
 Timestamp('2023-07-25 00:00:00'),
 Timestamp('2023-07-28 00:00:00'),
 Timestamp('2023-07-28 00:00:00'),
 Timestamp('2023-07-28 00:00:00'),
 Timestamp('2023-08-02 00:00:00'),
 Timestamp('2023-08-02 00:00:00'),
 Timestamp('2023-08-04 00:00:00'),
 Timestamp('2023-08-04 00:00:00'),
 Timestamp('2023-08-14 00:00:00'),
 Timestamp('2023-08-15 00:00:00'),
 Timestamp('2023-08-21 00:00:00'),
 Timestamp('2023-08-22 00:00:00'),
 Timestamp('2023-08-31 00:00:00'),
 Timestamp('2023-09-07 00:00:00'),
 Timestamp('2023-09-20 00:00:00'),
 Timestamp('2023-09-21 00:00:00'),
 Timestamp('2023-09-21 00:00:00'),
 Timestamp('2023-10-05 00:00:00'),
 Timestamp('2023-10-05 00:00:00'),
 Timestamp('2023-10-05 00:00:00'),
 Timestamp('2023-10-06 00:00:00'),
 Timestamp('2023-10-12 00:00:00'),
 Timestamp('2023-10-27 00:00:00'),
 Timestamp('2023-10-27 00:00:00'),
 Timestamp('2023-12-20 00:00:00'),
 Timestamp('2023-12-21 00:00:00'),
 Timestamp('2024-02-26 00:00:00'),
 Timestamp('2024-03-21 00:00:00'),
 Timestamp('2024-03-27 00:00:00'),
 Timestamp('2024-03-27 00:00:00'),
 Timestamp('2024-04-10 00:00:00'),
 Timestamp('2024-05-02 00:00:00'),
 Timestamp('2024-05-09 00:00:00'),
 Timestamp('2024-05-23 00:00:00'),
 Timestamp('2024-05-30 00:00:00'),
 Timestamp('2024-05-30 00:00:00'),
 Timestamp('2024-06-05 00:00:00'),
 Timestamp('2024-06-08 00:00:00'),
 Timestamp('2024-06-13 00:00:00'),
 Timestamp('2024-06-20 00:00:00'),
 Timestamp('2024-06-21 00:00:00'),
 Timestamp('2024-07-05 00:00:00'),
 Timestamp('2024-07-05 00:00:00'),
 Timestamp('2024-07-05 00:00:00'),
 Timestamp('2024-07-05 00:00:00'),
 Timestamp('2024-07-05 00:00:00'),
 Timestamp('2024-07-15 00:00:00'),
 Timestamp('2024-07-22 00:00:00'),
 Timestamp('2024-07-22 00:00:00'),
 Timestamp('2024-07-24 00:00:00'),
 Timestamp('2024-07-24 00:00:00'),
 Timestamp('2024-07-24 00:00:00'),
 Timestamp('2024-07-24 00:00:00'),
 Timestamp('2024-07-26 00:00:00'),
 Timestamp('2024-07-26 00:00:00'),
 Timestamp('2024-08-15 00:00:00'),
 Timestamp('2024-08-19 00:00:00'),
 Timestamp('2024-08-19 00:00:00'),
 Timestamp('2024-08-19 00:00:00'),
 Timestamp('2024-08-29 00:00:00'),
 Timestamp('2024-08-29 00:00:00'),
 Timestamp('2024-08-30 00:00:00'),
 Timestamp('2024-08-30 00:00:00'),
 Timestamp('2024-09-13 00:00:00'),
 Timestamp('2024-09-23 00:00:00'),
 Timestamp('2024-10-03 00:00:00'),
 Timestamp('2024-10-16 00:00:00'),
 Timestamp('2024-10-22 00:00:00'),
 Timestamp('2024-10-23 00:00:00'),
 Timestamp('2024-10-23 00:00:00'),
 Timestamp('2024-10-23 00:00:00'),
 Timestamp('2024-11-15 00:00:00'),
 Timestamp('2024-11-15 00:00:00'),
 Timestamp('2024-11-29 00:00:00'),
 Timestamp('2025-01-16 00:00:00'),
 Timestamp('2025-02-20 00:00:00'),
 Timestamp('2025-03-25 00:00:00'),
 Timestamp('2025-03-25 00:00:00'),
 Timestamp('2025-03-25 00:00:00'),
 Timestamp('2025-04-30 00:00:00'),
 Timestamp('2025-06-03 00:00:00'),
 Timestamp('2025-06-18 00:00:00'),
 Timestamp('2025-06-18 00:00:00'),
 Timestamp('2025-06-20 00:00:00'),
 Timestamp('2025-07-15 00:00:00'),
 Timestamp('2025-07-15 00:00:00'),
 Timestamp('2025-07-22 00:00:00'),
 Timestamp('2025-09-03 00:00:00'),
 Timestamp('2025-09-09 00:00:00'),
 Timestamp('2025-09-09 00:00:00'),
 Timestamp('2025-09-15 00:00:00'),
 Timestamp('2025-09-15 00:00:00'),

### Number of Violations by Building

In [61]:
summary = (
    filtered_merged_df.groupby(
        ['bin']
        )['disposition_code']
    .value_counts()
    .unstack(fill_value=0)
    .reset_index()
)
summary['total_violation'] = (summary[['A1', 'A8', 'A9', 'H3']].sum(axis=1))
summary

disposition_code      bin  A1  A8  A9  H3  total_violation
0                 1000018   0   1   0   0                1
1                 1000020   0   3   0   0                3
2                 1000793   0   6   0   0                6
3                 1000804   0   5   0   0                5
4                 1000807   0   3   0   0                3
..                    ...  ..  ..  ..  ..              ...
275               3319419   0   1   0   0                1
276               3393804   0   3   0   0                3
277               4307108   0   1   0   0                1
278               4607310   0   2   0   0                2
279               4615634   0   3   0   0                3

[280 rows x 6 columns]

### data cleaning

In [131]:
building_info = (
    filtered_merged_df[
        [
            'bin',
            'building_name',
            'building_address_with_zip',
            'year_completed',
            'public_space_type',
            'hour_of_access_required',
            'size_required',
            'total_sf',
            'amenities_required',
            'physically_disabled',
            'developer',
            'complaint_number',
            'latitude',
            'longitude'
        ]
    ]
    .drop_duplicates('bin')
)

summary_final = pd.merge(summary,
    building_info,
    on='bin',
    how='left'
)

date_range = (
    filtered_merged_df.groupby('bin')['disposition_date']
    .agg(
        first_disposition_date='min',
        last_disposition_date='max'
    )
        .reset_index()
)

cleaned_summary = pd.merge(summary_final, date_range, on='bin', how='left')
cleaned_summary.to_csv('merged_POPS_DOB.csv', index=False)
cleaned_summary

,bin,A1,A8,A9,H3,total_violation,building_name,building_address_with_zip,year_completed,public_space_type,...,size_required,total_sf,amenities_required,physically_disabled,developer,complaint_number,latitude,longitude,first_disposition_date,last_disposition_date
0,1000018,0,1,0,0,1,1 State Street Plaza,"1 STATE STREET, New York, NY 10004",1970,Arcade; Plaza,...,Arcade 731.00 sf; Plaza 8976.80 sf,9707.8,None,Full/Partial,NaN,1513911,40.70276,-74.013301,2019-06-24,2019-06-24
1,1000020,0,3,0,0,3,NaN,"17 STATE STREET, New York, NY 10004",1987,Arcade; Public Exhibit Space; Sidewalk Widenin...,...,Arcade 6198.00 sf; Public Exhibit Space 0.00 s...,14185.0,Lighting; Litter Receptacles; None; Other Requ...,Full/Partial,William Kaufman,1465311,40.702892,-74.013878,2017-11-13,2024-09-13
2,1000793,0,6,0,0,6,NaN,"90 WASHINGTON STREET, New York, NY 10006",1968,Plaza,...,Plaza 8789.00 sf,8789.0,Bicycle Parking; Lighting; Planting; Plaque/Si...,Full/Partial,NaN,1465586,40.708074,-74.01485,2016-06-22,2024-05-09
3,1000804,0,5,0,0,5,45 Broadway Atrium,"45 BROADWAY, New York, NY 10006",1983,Arcade; Shopping Arcade,...,Arcade 1983.00 sf; Shopping Arcade 81.68 sf,2064.68,Escalator; Subway,Full/Partial,"HRO International, Ltd.",1463410,40.706542,-74.013266,2017-10-20,2025-10-14
4,1000807,0,3,0,0,3,1 Exchange Plaza,"55 BROADWAY, New York, NY 10006",1983,Other Public Access Areas; Urban Plaza,...,Other Public Access Areas 0.00 sf; Urban Plaza...,1726.0,Escalator; Lighting; Litter Receptacles; Plant...,Full/Partial,NaN,1463409,40.706855,-74.013024,2017-10-20,2024-07-24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,3319419,0,1,0,0,1,Livingston Plaza,"130 LIVINGSTON STREET, Brooklyn, NY 11201",1991,Plaza,...,Plaza 19201.00 sf,19201.0,Lighting; Litter Receptacles; Other Required; ...,Full/Partial,Cohen Brothers,3707836,40.690409,-73.988771,2019-07-01,2019-07-01
276,3393804,0,3,0,0,3,Forte,"230 ASHLAND PLACE, Brooklyn, NY 11217",2007,Residential Plaza,...,Residential Plaza 3960.00 sf,3960.0,Bicycle Parking; Drinking Fountain; Lighting; ...,Full/Partial,The Clarett Group,3A20463,40.688253,-73.978636,2019-07-01,2025-07-15
277,4307108,0,1,0,0,1,Citicorp at Court Square,"1 COURT SQUARE, Queens, NY 11101",1989,Landscaped Public Open Space; Pedestrian Circu...,...,Landscaped Public Open Space 0.00 sf; Pedestri...,0.0,Escalator; Subway; Trees on Street; Trees with...,Full/Partial,NaN,4776093,40.747058,-73.944064,2019-07-01,2019-07-01
278,4607310,0,2,0,0,2,Flushing Commons,"138-35 39 AVENUE, Queens, NY 11354",NaN,Publicly Accessible Open Space,...,NaN,<NA>,NaN,NaN,NaN,4819259,40.761235,-73.827713,2020-10-05,2023-01-12
279,4615634,0,3,0,0,3,Rego Park Mall,"61-01 JUNCTION BOULEVARD, Queens, NY 11374",2010,Publicly Accessible Pedestrian Area,...,Publicly Accessible Pedestrian Area 0.00 sf,0.0,Elevator; Escalator; Lighting; Other Required;...,Unknown,Vornado Realty Trust,4940160,40.733127,-73.863031,2023-01-12,2023-10-12

In [119]:
cleaned_summary['total_violation'].value_counts()

total_violation
1    126
2     75
3     44
5     14
4     12
6      5
7      4
Name: count, dtype: int64

In [132]:
cleaned_summary['complaint_number'].unique()

<StringArray>
['1513911', '1465311', '1465586', '1463410', '1463409', '1461697', '1464297',
 '1531289', '1512316', '1465309',
 ...
 '1672813', '1550690', '3707837', '3939566', '3979915', '3707836', '3A20463',
 '4776093', '4819259', '4940160']
Length: 280, dtype: str

## Get OATH data
### sort by issuing_agency=DEPARTMENT OF BUILDINGS

In [14]:
# Example authenticated client (needed for non-public datasets):
client = Socrata('data.cityofnewyork.us',
                  os.environ.get('API_KEY_2'),
                  username=os.environ.get('USER_NAME'),
                  password=os.environ.get('PASS')
                )

# First 10000 results, returned as JSON from API / converted to Python list of
# dictionaries by sodapy.
results = client.get("jz4z-kudi",
                     where="issuing_agency = 'DEPARTMENT OF BUILDINGS'",
                     limit=10000)

# Convert to pandas DataFrame
results_df4 = pd.DataFrame.from_records(results)
results_df4

,ticket_number,violation_date,violation_time,issuing_agency,respondent_last_name,balance_due,violation_location_borough,violation_location_block_no,violation_location_lot_no,violation_location_house,...,respondent_address_or_facility_number_for_fdny_and_dob_tickets,date_judgment_docketed,charge_2_infraction_amount,charge_2_code,charge_2_code_section,charge_2_code_description,charge_3_infraction_amount,charge_3_code,charge_3_code_section,charge_3_code_description
0,0213713574,2026-04-29T00:00:00.000,10:42:00,DEPARTMENT OF BUILDINGS,CHEN,5000,QUEENS,01877,0039,94-39,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0213670977,2026-04-10T00:00:00.000,14:08:00,DEPARTMENT OF BUILDINGS,RHEA RENOVATIONS INC,5000,STATEN IS,NaN,NaN,1063,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0204446202,2026-04-02T00:00:00.000,11:33:00,DEPARTMENT OF BUILDINGS,A E PIPING AND HEATING INC,5000,BROOKLYN,04759,0059,651,...,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0204446211,2026-04-02T00:00:00.000,11:40:00,DEPARTMENT OF BUILDINGS,A E PIPING AND HEATING INC,5030,BROOKLYN,04759,0059,651,...,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0204446220,2026-04-02T00:00:00.000,13:00:00,DEPARTMENT OF BUILDINGS,A E PIPING AND HEATING INC,5000,BROOKLYN,04759,0059,651,...,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2920,0181506445,NaN,00:00:00,DEPARTMENT OF BUILDINGS,VISCONTI,0,NOT NYC,NaN,NaN,D ST,...,HOWAR,NaN,4800,A1C7,27-3017,PERFORMED UNLICENSED ELECTRICAL WORK,NaN,NaN,NaN,NaN
2921,0181502274,NaN,00:00:00,DEPARTMENT OF BUILDINGS,ISLAM,0,NOT NYC,NaN,NaN,LACE,...,MIDDL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2922,0181509745,NaN,00:00:00,DEPARTMENT OF BUILDINGS,ISOLDA,0,NOT NYC,NaN,NaN,43RD ST,...,STATE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2923,0181503118,NaN,00:00:00,DEPARTMENT OF BUILDINGS,WILLIAMS,0,NOT NYC,NaN,NaN,43RD ST,...,BROOK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2924,0213651011,NaN,13:30:00,DEPARTMENT OF BUILDINGS,CHOLULA BARBER SHOP,0,BRONX,03345,0001,3125,...,NaN,2021-11-30T00:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
results_df4.columns.tolist()

['ticket_number',
 'violation_date',
 'violation_time',
 'issuing_agency',
 'respondent_last_name',
 'balance_due',
 'violation_location_borough',
 'violation_location_block_no',
 'violation_location_lot_no',
 'violation_location_house',
 'violation_location_street_name',
 'violation_location_city',
 'violation_location_zip_code',
 'violation_location_state_name',
 'respondent_address_borough',
 'respondent_address_house',
 'respondent_address_zip_code',
 'hearing_status',
 'hearing_date',
 'hearing_time',
 'total_violation_amount',
 'violation_details',
 'penalty_imposed',
 'paid_amount',
 'additional_penalties_or_late_fees',
 'compliance_status',
 'charge_1_code',
 'charge_1_code_section',
 'charge_1_code_description',
 'charge_1_infraction_amount',
 'scheduled_hearing_location',
 'hearing_result',
 'decision_location_borough',
 'decision_date',
 'respondent_address_or_facility_number_for_fdny_and_dob_tickets',
 'date_judgment_docketed',
 'charge_2_infraction_amount',
 'charge_2_code',
 'charge_2_code_section',
 'charge_2_code_description',
 'charge_3_infraction_amount',
 'charge_3_code',
 'charge_3_code_section',
 'charge_3_code_description']

In [16]:
results_df4['violation_location_city'].value_counts()

violation_location_city
BROOKLYN           853
NEW YORK           642
BRONX              299
FAR ROCKAWAY       211
FLUSHING           163
RIDGEWOOD           73
JAMAICA             69
STATEN ISLAND       64
WOODSIDE            52
ASTORIA             42
FOREST HILLS        42
QUEENS              37
FRESH MEADOWS       28
JACKSON HEIGHTS     27
CORONA              25
OZONE PARK          25
LONG ISLAND CIT     23
REGO PARK           18
ELMHURST            16
BAYSIDE             14
RICHMOND HILL       14
MASPETH             13
QUEENS VILLAGE      12
OAKLAND GARDENS     12
SOUTH OZONE PAR     10
WHITESTONE          10
SOUTH RICHMOND      10
MIDDLE VILLAGE       8
LITTLE NECK          8
WOODHAVEN            7
SPRINGFIELD GDN      7
BELLEROSE            7
SUNNYSIDE            7
HOWARD BEACH         6
ROCKAWAY PARK        6
EAST ELMHURST        5
HOLLIS               3
KEW GARDENS          3
SAINT ALBANS         3
BX                   3
ROSEDALE             2
BREEZY POINT         1
SI                   1
GLEN OAKS            1
MANHATTAN            1
Name: count, dtype: int64

In [17]:
results_df4['address'] = results_df4['violation_location_house'] + results_df4['violation_location_street_name'] + results_df4['violation_location_zip_code']
results_df4

,ticket_number,violation_date,violation_time,issuing_agency,respondent_last_name,balance_due,violation_location_borough,violation_location_block_no,violation_location_lot_no,violation_location_house,...,date_judgment_docketed,charge_2_infraction_amount,charge_2_code,charge_2_code_section,charge_2_code_description,charge_3_infraction_amount,charge_3_code,charge_3_code_section,charge_3_code_description,address
0,0213713574,2026-04-29T00:00:00.000,10:42:00,DEPARTMENT OF BUILDINGS,CHEN,5000,QUEENS,01877,0039,94-39,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94-3950 AVENUE11373
1,0213670977,2026-04-10T00:00:00.000,14:08:00,DEPARTMENT OF BUILDINGS,RHEA RENOVATIONS INC,5000,STATEN IS,NaN,NaN,1063,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1063RICHMOND RD STATEN ISLAND10304
2,0204446202,2026-04-02T00:00:00.000,11:33:00,DEPARTMENT OF BUILDINGS,A E PIPING AND HEATING INC,5000,BROOKLYN,04759,0059,651,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,651EAST 48 STREET11203
3,0204446211,2026-04-02T00:00:00.000,11:40:00,DEPARTMENT OF BUILDINGS,A E PIPING AND HEATING INC,5030,BROOKLYN,04759,0059,651,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,651EAST 48 STREET11203
4,0204446220,2026-04-02T00:00:00.000,13:00:00,DEPARTMENT OF BUILDINGS,A E PIPING AND HEATING INC,5000,BROOKLYN,04759,0059,651,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,651EAST 48 STREET11203
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2920,0181506445,NaN,00:00:00,DEPARTMENT OF BUILDINGS,VISCONTI,0,NOT NYC,NaN,NaN,D ST,...,NaN,4800,A1C7,27-3017,PERFORMED UNLICENSED ELECTRICAL WORK,NaN,NaN,NaN,NaN,D STQUEENS NY07142
2921,0181502274,NaN,00:00:00,DEPARTMENT OF BUILDINGS,ISLAM,0,NOT NYC,NaN,NaN,LACE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LACEQUEENS NY04142
2922,0181509745,NaN,00:00:00,DEPARTMENT OF BUILDINGS,ISOLDA,0,NOT NYC,NaN,NaN,43RD ST,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43RD STQUEENS NY04282
2923,0181503118,NaN,00:00:00,DEPARTMENT OF BUILDINGS,WILLIAMS,0,NOT NYC,NaN,NaN,43RD ST,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43RD STQUEENS NY04282
2924,0213651011,NaN,13:30:00,DEPARTMENT OF BUILDINGS,CHOLULA BARBER SHOP,0,BRONX,03345,0001,3125,...,2021-11-30T00:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3125HULL AVENUE10467

In [18]:
results_df4['address_key'] = (
    results_df4['address']
    .astype(str)
    .str.upper()
    .str.replace(r"\s+", '', regex=True)
)
results_df4

,ticket_number,violation_date,violation_time,issuing_agency,respondent_last_name,balance_due,violation_location_borough,violation_location_block_no,violation_location_lot_no,violation_location_house,...,charge_2_infraction_amount,charge_2_code,charge_2_code_section,charge_2_code_description,charge_3_infraction_amount,charge_3_code,charge_3_code_section,charge_3_code_description,address,address_key
0,0213713574,2026-04-29T00:00:00.000,10:42:00,DEPARTMENT OF BUILDINGS,CHEN,5000,QUEENS,01877,0039,94-39,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94-3950 AVENUE11373,94-3950AVENUE11373
1,0213670977,2026-04-10T00:00:00.000,14:08:00,DEPARTMENT OF BUILDINGS,RHEA RENOVATIONS INC,5000,STATEN IS,NaN,NaN,1063,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1063RICHMOND RD STATEN ISLAND10304,1063RICHMONDRDSTATENISLAND10304
2,0204446202,2026-04-02T00:00:00.000,11:33:00,DEPARTMENT OF BUILDINGS,A E PIPING AND HEATING INC,5000,BROOKLYN,04759,0059,651,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,651EAST 48 STREET11203,651EAST48STREET11203
3,0204446211,2026-04-02T00:00:00.000,11:40:00,DEPARTMENT OF BUILDINGS,A E PIPING AND HEATING INC,5030,BROOKLYN,04759,0059,651,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,651EAST 48 STREET11203,651EAST48STREET11203
4,0204446220,2026-04-02T00:00:00.000,13:00:00,DEPARTMENT OF BUILDINGS,A E PIPING AND HEATING INC,5000,BROOKLYN,04759,0059,651,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,651EAST 48 STREET11203,651EAST48STREET11203
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2920,0181506445,NaN,00:00:00,DEPARTMENT OF BUILDINGS,VISCONTI,0,NOT NYC,NaN,NaN,D ST,...,4800,A1C7,27-3017,PERFORMED UNLICENSED ELECTRICAL WORK,NaN,NaN,NaN,NaN,D STQUEENS NY07142,DSTQUEENSNY07142
2921,0181502274,NaN,00:00:00,DEPARTMENT OF BUILDINGS,ISLAM,0,NOT NYC,NaN,NaN,LACE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LACEQUEENS NY04142,LACEQUEENSNY04142
2922,0181509745,NaN,00:00:00,DEPARTMENT OF BUILDINGS,ISOLDA,0,NOT NYC,NaN,NaN,43RD ST,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43RD STQUEENS NY04282,43RDSTQUEENSNY04282
2923,0181503118,NaN,00:00:00,DEPARTMENT OF BUILDINGS,WILLIAMS,0,NOT NYC,NaN,NaN,43RD ST,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43RD STQUEENS NY04282,43RDSTQUEENSNY04282
2924,0213651011,NaN,13:30:00,DEPARTMENT OF BUILDINGS,CHOLULA BARBER SHOP,0,BRONX,03345,0001,3125,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3125HULL AVENUE10467,3125HULLAVENUE10467

## merge POPS, DOB_complaint and OATH(by address)

In [43]:
merged_df2 = pd.merge(merged_df, results_df4, on='address_key', how='inner')
merged_df2.to_csv('POPS_DOB_OATH.csv', index=False)

In [20]:
merged_df2.columns.tolist()

['building_name',
 'pops_number',
 'building_address_with_zip',
 'year_completed',
 'public_space_type',
 'total_sf',
 'size_required',
 'hour_of_access_required',
 'amenities_required',
 'physically_disabled',
 'developer',
 'borough_name',
 'latitude',
 'longitude',
 'bin',
 'bbl',
 'address_x',
 'address_key',
 'complaint_number',
 'status',
 'date_entered',
 'house_number',
 'zip_code',
 'house_street',
 'community_board',
 'complaint_category',
 'unit',
 'disposition_date',
 'disposition_code',
 'inspection_date',
 'dobrundate',
 'special_district',
 'ticket_number',
 'violation_date',
 'violation_time',
 'issuing_agency',
 'respondent_last_name',
 'balance_due',
 'violation_location_borough',
 'violation_location_block_no',
 'violation_location_lot_no',
 'violation_location_house',
 'violation_location_street_name',
 'violation_location_city',
 'violation_location_zip_code',
 'violation_location_state_name',
 'respondent_address_borough',
 'respondent_address_house',
 'respondent_address_zip_code',
 'hearing_status',
 'hearing_date',
 'hearing_time',
 'total_violation_amount',
 'violation_details',
 'penalty_imposed',
 'paid_amount',
 'additional_penalties_or_late_fees',
 'compliance_status',
 'charge_1_code',
 'charge_1_code_section',
 'charge_1_code_description',
 'charge_1_infraction_amount',
 'scheduled_hearing_location',
 'hearing_result',
 'decision_location_borough',
 'decision_date',
 'respondent_address_or_facility_number_for_fdny_and_dob_tickets',
 'date_judgment_docketed',
 'charge_2_infraction_amount',
 'charge_2_code',
 'charge_2_code_section',
 'charge_2_code_description',
 'charge_3_infraction_amount',
 'charge_3_code',
 'charge_3_code_section',
 'charge_3_code_description',
 'address_y']

In [39]:
merged_df2['disposition_code'].value_counts()

disposition_code
I2    26
A8    21
I3     6
I1     3
H1     3
G5     2
A1     1
A9     1
Name: count, dtype: int64

##### I2=No Violation Warranted for Complaint at Time of Inspection
##### A8=OATH Violation Served★
##### I3=Compliance Inspection Performed
##### I1=Complaint Unsubstantiated Based on Department Records
##### H1=Please See Complaint Number
##### G5=Complaint Referred to New York Police Department (NYPD)
##### A1=Buildings Violation(s) Served★
##### A9=OATH and DOB Violations Served★

### Focus on vialation

In [70]:
target_code2 = ['A8', 'A1', 'A9']
filtered_merged_df2 = merged_df2[merged_df2['disposition_code'].isin(target_code2)]
filtered_merged_df2

,building_name,pops_number,building_address_with_zip,year_completed,public_space_type,total_sf,size_required,hour_of_access_required,amenities_required,physically_disabled,...,date_judgment_docketed,charge_2_infraction_amount,charge_2_code,charge_2_code_section,charge_2_code_description,charge_3_infraction_amount,charge_3_code,charge_3_code_section,charge_3_code_description,address_y
6,Marlborough,M060037,"245 EAST 40 STREET, New York, NY 10016",1973,Arcade; Plaza,8153.3,Arcade 648.00 sf; Plaza 7505.30 sf,24 Hours,None,Full/Partial,...,2021-12-31T00:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,245EAST 40 STREET10016
8,Two Gold,M010050,"2 GOLD STREET, New York, NY 10038",2005,Urban Plaza,8130.0,Urban Plaza 8130.00 sf,24 Hours,Artwork; Lighting; Litter Receptacles; Plantin...,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2GOLD STREET10038
9,Two Gold,M010050,"2 GOLD STREET, New York, NY 10038",2005,Urban Plaza,8130.0,Urban Plaza 8130.00 sf,24 Hours,Artwork; Lighting; Litter Receptacles; Plantin...,Full/Partial,...,2022-06-30T00:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2GOLD STREET10038
16,Two Gold,M010050,"2 GOLD STREET, New York, NY 10038",2005,Urban Plaza,8130.0,Urban Plaza 8130.00 sf,24 Hours,Artwork; Lighting; Litter Receptacles; Plantin...,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2GOLD STREET10038
17,Two Gold,M010050,"2 GOLD STREET, New York, NY 10038",2005,Urban Plaza,8130.0,Urban Plaza 8130.00 sf,24 Hours,Artwork; Lighting; Litter Receptacles; Plantin...,Full/Partial,...,2022-06-30T00:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2GOLD STREET10038
24,Two Gold,M010050,"2 GOLD STREET, New York, NY 10038",2005,Urban Plaza,8130.0,Urban Plaza 8130.00 sf,24 Hours,Artwork; Lighting; Litter Receptacles; Plantin...,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2GOLD STREET10038
25,Two Gold,M010050,"2 GOLD STREET, New York, NY 10038",2005,Urban Plaza,8130.0,Urban Plaza 8130.00 sf,24 Hours,Artwork; Lighting; Litter Receptacles; Plantin...,Full/Partial,...,2022-06-30T00:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2GOLD STREET10038
28,Two Gold,M010050,"2 GOLD STREET, New York, NY 10038",2005,Urban Plaza,8130.0,Urban Plaza 8130.00 sf,24 Hours,Artwork; Lighting; Litter Receptacles; Plantin...,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2GOLD STREET10038
29,Two Gold,M010050,"2 GOLD STREET, New York, NY 10038",2005,Urban Plaza,8130.0,Urban Plaza 8130.00 sf,24 Hours,Artwork; Lighting; Litter Receptacles; Plantin...,Full/Partial,...,2022-06-30T00:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2GOLD STREET10038
32,NaN,M060006,"166 EAST 34 STREET, New York, NY 10016",1974,Plaza,4412.4,Plaza 4412.40 sf,24 Hours,Plaque/Sign,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,166EAST 34 STREET10016
34,NaN,M060006,"166 EAST 34 STREET, New York, NY 10016",1974,Plaza,4412.4,Plaza 4412.40 sf,24 Hours,Plaque/Sign,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,166EAST 34 STREET10016
39,NaN,M060006,"166 EAST 34 STREET, New York, NY 10016",1974,Plaza,4412.4,Plaza 4412.40 sf,24 Hours,Plaque/Sign,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,166EAST 34 STREET10016
41,NaN,M060006,"166 EAST 34 STREET, New York, NY 10016",1974,Plaza,4412.4,Plaza 4412.40 sf,24 Hours,Plaque/Sign,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,166EAST 34 STREET10016
43,NaN,M060006,"166 EAST 34 STREET, New York, NY 10016",1974,Plaza,4412.4,Plaza 4412.40 sf,24 Hours,Plaque/Sign,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,166EAST 34 STREET10016
48,NaN,M050072,"50 LEXINGTON AVENUE, New York, NY 10010",1987,Public Access Areas; Residential Plaza,4304.5,Public Access Areas 4304.50 sf; Residential Pl...,24 Hours,Bicycle Parking; Drinking Fountain; Lighting; ...,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50LEXINGTON AVENUE10010
49,NaN,M050072,"50 LEXINGTON AVENUE, New York, NY 10010",1987,Public Access Areas; Residential Plaza,4304.5,Public Access Areas 4304.50 sf; Residential Pl...,24 Hours,Bicycle Parking; Drinking Fountain; Lighting; ...,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50LEXINGTON AVENUE10010
52,NaN,M050072,"50 LEXINGTON AVENUE, New York, NY 10010",1987,Public Access Areas; Residential Plaza,4304.5,Public Access Areas 4304.50 sf; Residential Pl...,24 Hours,Bicycle Parking; Drinking Fountain; Lighting; ...,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50LEXINGTON AVENUE10010
53,NaN,M050072,"50 LEXINGTON AVENUE, New York, NY 10010",1987,Public Access Areas; Residential Plaza,4304.5,Public Access Areas 4304.50 sf; Residential Pl...,24 Hours,Bicycle Parking; Drinking Fountain; Lighting; ...,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50LEXINGTON AVENUE10010
55,Murray Hill House,M060008,"132 EAST 35 STREET, New York, NY 10016",1969,Plaza,3966.99,Plaza 3966.99 sf,24 Hours,None,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,132EAST 35 STREET10016
57,Crystal House,M060012,"200 EAST 24 STREET, New York, NY 10010",1972,Plaza,3079.22,Plaza 3079.22 sf,24 Hours,None,Full/Partial,...,2022-08-31T00:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200EAST 24 STREET10010
59,Crystal House,M060012,"200 EAST 24 STREET, New York, NY 10010",1972,Plaza,3079.22,Plaza 3079.22 sf,24 Hours,None,Full/Partial,...,2022-08-31T00:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200EAST 24 STREET10010
61,Crystal House,M060012,"200 EAST 24 STREET, New York, NY 10010",1972,Plaza,3079.22,Plaza 3079.22 sf,24 Hours,None,Full/Partial,...,2022-08-31T00:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200EAST 24 STREET10010
62,Crystal House,M060012,"200 EAST 24 STREET, New York, NY 10010",1972,Plaza,3079.22,Plaza 3079.22 sf,24 Hours,None,Full/Partial,...,2022-08-31T00:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200EAST 24 STREET10010

### date_judgment_docketed

In [73]:
filtered_merged_df2['date_judgment_docketed'] = pd.to_datetime(filtered_merged_df2['date_judgment_docketed'])
filtered_merged_df2.sort_values('date_judgment_docketed')['date_judgment_docketed'].tolist()

[Timestamp('2021-12-31 00:00:00'),
 Timestamp('2022-06-30 00:00:00'),
 Timestamp('2022-06-30 00:00:00'),
 Timestamp('2022-06-30 00:00:00'),
 Timestamp('2022-06-30 00:00:00'),
 Timestamp('2022-08-31 00:00:00'),
 Timestamp('2022-08-31 00:00:00'),
 Timestamp('2022-08-31 00:00:00'),
 Timestamp('2022-08-31 00:00:00'),
 NaT,
 NaT,
 NaT,
 NaT,
 NaT,
 NaT,
 NaT,
 NaT,
 NaT,
 NaT,
 NaT,
 NaT,
 NaT,
 NaT]

### Number of violation by buildings

In [74]:
summary2 = (
    filtered_merged_df2.groupby(
        ['bin']
        )['disposition_code']
    .value_counts()
    .unstack(fill_value=0)
    .reset_index()
)
summary2['total_violation'] = (summary2[['A1', 'A8', 'A9']].sum(axis=1))
summary2

disposition_code      bin  A1  A8  A9  total_violation
0                 1018071   0   4   0                4
1                 1018502   1   4   0                5
2                 1018519   0   1   0                1
3                 1019782   0   3   1                4
4                 1037175   0   1   0                1
5                 1087146   0   8   0                8

#### data cleaning

In [123]:
building_info2 = (
    filtered_merged_df2[
        [
            'bin',
            'building_name',
            'building_address_with_zip',
            'year_completed',
            'public_space_type',
            'hour_of_access_required',
            'size_required',
            'total_sf',
            'amenities_required',
            'physically_disabled',
            'developer',
            'complaint_number',
            'penalty_imposed',
            'paid_amount',
            'latitude',
            'longitude'
        ]
    ]
    .drop_duplicates('bin')
)

summary_final2 = pd.merge(summary2,
    building_info2,
    on='bin',
    how='left'
)

date_range2 = (
    filtered_merged_df2.groupby('bin')['decision_date']
    .agg(
        first_decision_date='min',
        last_decision_date='max'
    )
        .reset_index()
)

cleaned_summary2 = pd.merge(summary_final2, date_range2, on='bin', how='left')
cleaned_summary2.to_csv('merged_POPS_DOB_OATH,csv', index=False)

In [27]:
merged_df2['penalty_imposed'].value_counts()

penalty_imposed
1000    36
0       22
2000     5
Name: count, dtype: int64

In [23]:
merged_df2['paid_amount'].value_counts()

paid_amount
0       22
1000    18
1138    12
1002     6
2061     5
Name: count, dtype: int64

In [24]:
merged_df2['decision_date'].value_counts()

decision_date
2022-04-06T00:00:00.000    12
2022-03-03T00:00:00.000    12
2022-05-24T00:00:00.000     6
2021-09-29T00:00:00.000     5
2022-07-14T00:00:00.000     5
2022-01-11T00:00:00.000     5
Name: count, dtype: int64

In [25]:
merged_df2['building_address_with_zip'].value_counts()

building_address_with_zip
2 GOLD STREET, New York, NY 10038          24
166 EAST 34 STREET, New York, NY 10016     12
50 LEXINGTON AVENUE, New York, NY 10010    10
200 EAST 24 STREET, New York, NY 10010      6
245 EAST 40 STREET, New York, NY 10016      5
345 PARK AVENUE, New York, NY 10154         3
132 EAST 35 STREET, New York, NY 10016      3
Name: count, dtype: int64

In [53]:
summary2 = (
    merged_df2.groupby(
        ['bin'])['paid_amount']
    .value_counts()
    .unstack(fill_value=0)
    .reset_index()
)
summary2

paid_amount      bin  1000  2061   0  1138  1002
0            1018071     0     0  10     0     0
1            1018502    12     0   0     0     0
2            1018519     3     0   0     0     0
3            1019782     0     0   0     0     6
4            1036460     3     0   0     0     0
5            1037175     0     5   0     0     0
6            1087146     0     0  12    12     0

## Get DOB ECB Violations data

In [78]:
# Example authenticated client (needed for non-public datasets):
client = Socrata('data.cityofnewyork.us',
                  os.environ.get('API_KEY_2'),
                  username=os.environ.get('USER_NAME'),
                  password=os.environ.get('PASS')
                )

# First 1820879 results, returned as JSON from API / converted to Python list of
# dictionaries by sodapy.
results = client.get("6bgk-3dad", limit=1830000)

# Convert to pandas DataFrame
results_df_ECB = pd.DataFrame.from_records(results)
results_df_ECB

,isn_dob_bis_extract,ecb_violation_number,ecb_violation_status,dob_violation_number,bin,boro,block,lot,hearing_date,hearing_time,...,infraction_code6,section_law_description6,infraction_code7,section_law_description7,infraction_code8,section_law_description8,infraction_code9,section_law_description9,infraction_code10,section_law_description10
0,1075005,34044233R,RESOLVE,112790CA4PR04,1006588,1,00460,0029,19910509,830,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1082681,34833639Z,RESOLVE,012810CJG03,1060779,1,02044,0020,20100325,1030,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1226423,34870720Z,RESOLVE,081910CSTFCS15,3071867,3,03150,0002,20101018,830,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1215996,34056687J,RESOLVE,051491C04EP02,3075774,3,03311,0001,19911230,1200,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1652465,34793711K,RESOLVE,092109C12JK02,4214942,4,10052,0023,20100406,830,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1821089,1828288,39549001N,RESOLVE,NaN,4437698,4,03408,0048,20260317,930,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1821090,1805945,35534561Y,RESOLVE,072921ASPOJR03,3425505,3,03170,0026,20211208,830,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1821091,1829669,39542081K,RESOLVE,NaN,5033748,5,01965,0049,20260320,830,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1821092,1828549,35644642N,ACTIVE,01222022EE502RH2,NaN,5,NaN,NaN,20221116,830,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1821093,1818885,39186073M,ACTIVE,NaN,3346868,3,04595,0215,20270119,830,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## merge POPS_DOB_complaint and ECB(by bin)

In [79]:
merged_df3 = pd.merge(merged_df, results_df_ECB, on='bin', how='inner')
merged_df3

,building_name,pops_number,building_address_with_zip,year_completed,public_space_type,total_sf,size_required,hour_of_access_required,amenities_required,physically_disabled,...,infraction_code6,section_law_description6,infraction_code7,section_law_description7,infraction_code8,section_law_description8,infraction_code9,section_law_description9,infraction_code10,section_law_description10
0,NaN,M010025,"55 WATER STREET, New York, NY 10041",1970,Arcade; Elevated Plaza; Plaza,85046.0,Arcade 10254.00 sf; Elevated Plaza 41485.00 sf...,24 Hours; Closing for Events; Restricted Hours,Escalator; Food Service; Lighting; None; Other...,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,M010025,"55 WATER STREET, New York, NY 10041",1970,Arcade; Elevated Plaza; Plaza,85046.0,Arcade 10254.00 sf; Elevated Plaza 41485.00 sf...,24 Hours; Closing for Events; Restricted Hours,Escalator; Food Service; Lighting; None; Other...,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,M010025,"55 WATER STREET, New York, NY 10041",1970,Arcade; Elevated Plaza; Plaza,85046.0,Arcade 10254.00 sf; Elevated Plaza 41485.00 sf...,24 Hours; Closing for Events; Restricted Hours,Escalator; Food Service; Lighting; None; Other...,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,M010025,"55 WATER STREET, New York, NY 10041",1970,Arcade; Elevated Plaza; Plaza,85046.0,Arcade 10254.00 sf; Elevated Plaza 41485.00 sf...,24 Hours; Closing for Events; Restricted Hours,Escalator; Food Service; Lighting; None; Other...,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,M010025,"55 WATER STREET, New York, NY 10041",1970,Arcade; Elevated Plaza; Plaza,85046.0,Arcade 10254.00 sf; Elevated Plaza 41485.00 sf...,24 Hours; Closing for Events; Restricted Hours,Escalator; Food Service; Lighting; None; Other...,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111248,NaN,M050115,"1241 BROADWAY, New York, NY 10001",NaN,Arcade,<NA>,NaN,NaN,NaN,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111249,NaN,M050115,"1241 BROADWAY, New York, NY 10001",NaN,Arcade,<NA>,NaN,NaN,NaN,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111250,NaN,M050115,"1241 BROADWAY, New York, NY 10001",NaN,Arcade,<NA>,NaN,NaN,NaN,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111251,NaN,M050115,"1241 BROADWAY, New York, NY 10001",NaN,Arcade,<NA>,NaN,NaN,NaN,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111252,NaN,M050115,"1241 BROADWAY, New York, NY 10001",NaN,Arcade,<NA>,NaN,NaN,NaN,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [81]:
merged_df3.columns.tolist()

['building_name',
 'pops_number',
 'building_address_with_zip',
 'year_completed',
 'public_space_type',
 'total_sf',
 'size_required',
 'hour_of_access_required',
 'amenities_required',
 'physically_disabled',
 'developer',
 'borough_name',
 'latitude',
 'longitude',
 'bin',
 'bbl',
 'address',
 'address_key',
 'complaint_number',
 'status',
 'date_entered',
 'house_number',
 'zip_code',
 'house_street',
 'community_board',
 'complaint_category',
 'unit',
 'disposition_date',
 'disposition_code',
 'inspection_date',
 'dobrundate',
 'special_district',
 'isn_dob_bis_extract',
 'ecb_violation_number',
 'ecb_violation_status',
 'dob_violation_number',
 'boro',
 'block',
 'lot',
 'hearing_date',
 'hearing_time',
 'served_date',
 'issue_date',
 'severity',
 'violation_type',
 'respondent_name',
 'respondent_house_number',
 'respondent_street',
 'respondent_city',
 'respondent_zip',
 'violation_description',
 'penality_imposed',
 'amount_paid',
 'balance_due',
 'infraction_code1',
 'section_law_description1',
 'hearing_status',
 'certification_status',
 'aggravated_level',
 'infraction_code2',
 'section_law_description2',
 'infraction_code3',
 'section_law_description3',
 'infraction_code4',
 'section_law_description4',
 'infraction_code5',
 'section_law_description5',
 'infraction_code6',
 'section_law_description6',
 'infraction_code7',
 'section_law_description7',
 'infraction_code8',
 'section_law_description8',
 'infraction_code9',
 'section_law_description9',
 'infraction_code10',
 'section_law_description10']

In [95]:
merged_df3['bin'].unique()

<StringArray>
['1083346', '1024727', '1014387', '1088686', '1082816', '1000005', '1024812',
 '1043921', '1025450', '1079043',
 ...
 '3428715', '5164632', '1090263', '1089237', '1089695', '1090548', '1090647',
 '1077835', '3247051', '1090786']
Length: 375, dtype: str

In [83]:
filtered_merged_df3 = merged_df3[merged_df3['complaint_category'] == '78']
filtered_merged_df3

,building_name,pops_number,building_address_with_zip,year_completed,public_space_type,total_sf,size_required,hour_of_access_required,amenities_required,physically_disabled,...,infraction_code6,section_law_description6,infraction_code7,section_law_description7,infraction_code8,section_law_description8,infraction_code9,section_law_description9,infraction_code10,section_law_description10
0,NaN,M010025,"55 WATER STREET, New York, NY 10041",1970,Arcade; Elevated Plaza; Plaza,85046.0,Arcade 10254.00 sf; Elevated Plaza 41485.00 sf...,24 Hours; Closing for Events; Restricted Hours,Escalator; Food Service; Lighting; None; Other...,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,M010025,"55 WATER STREET, New York, NY 10041",1970,Arcade; Elevated Plaza; Plaza,85046.0,Arcade 10254.00 sf; Elevated Plaza 41485.00 sf...,24 Hours; Closing for Events; Restricted Hours,Escalator; Food Service; Lighting; None; Other...,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,M010025,"55 WATER STREET, New York, NY 10041",1970,Arcade; Elevated Plaza; Plaza,85046.0,Arcade 10254.00 sf; Elevated Plaza 41485.00 sf...,24 Hours; Closing for Events; Restricted Hours,Escalator; Food Service; Lighting; None; Other...,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,M010025,"55 WATER STREET, New York, NY 10041",1970,Arcade; Elevated Plaza; Plaza,85046.0,Arcade 10254.00 sf; Elevated Plaza 41485.00 sf...,24 Hours; Closing for Events; Restricted Hours,Escalator; Food Service; Lighting; None; Other...,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,M010025,"55 WATER STREET, New York, NY 10041",1970,Arcade; Elevated Plaza; Plaza,85046.0,Arcade 10254.00 sf; Elevated Plaza 41485.00 sf...,24 Hours; Closing for Events; Restricted Hours,Escalator; Food Service; Lighting; None; Other...,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111248,NaN,M050115,"1241 BROADWAY, New York, NY 10001",NaN,Arcade,<NA>,NaN,NaN,NaN,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111249,NaN,M050115,"1241 BROADWAY, New York, NY 10001",NaN,Arcade,<NA>,NaN,NaN,NaN,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111250,NaN,M050115,"1241 BROADWAY, New York, NY 10001",NaN,Arcade,<NA>,NaN,NaN,NaN,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111251,NaN,M050115,"1241 BROADWAY, New York, NY 10001",NaN,Arcade,<NA>,NaN,NaN,NaN,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111252,NaN,M050115,"1241 BROADWAY, New York, NY 10001",NaN,Arcade,<NA>,NaN,NaN,NaN,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### focus on vialation

In [80]:
merged_df3['disposition_code'].value_counts()

disposition_code
I2    53231
A8    25742
I3    11132
H1    11006
I1     3831
A1     1362
B1     1313
G5      879
A9      509
F3      360
F5      297
L2      234
G2      158
F6      125
B2      112
C2       55
J6       47
H3       41
L1       41
D5       35
F2       31
Name: count, dtype: int64

##### I2=No Violation Warranted for Complaint at Time of Inspection
##### A8=OATH Violation Served★
##### I3=Compliance Inspection Performed
##### H1=Please See Complaint Number
##### I1=Complaint Unsubstantiated Based on Department Records
##### A1=Buildings Violation(s) Served★
##### B1=Buildings Violation(s) Prepared and Attempt to Serve will be Made
##### G5=Complaint Referred to New York Police Department (NYPD)
##### A9=OATH and DOB Violations Served★
##### F3=Complaint Referred to NYC Department of Health and Mental Hygiene (DOHMH)
##### F5=Complaint Referred to Department of Sanitation (DOS)
##### L2=Stop Work Order Fully Rescinded
##### G2=Complaint Referred to Department of Parks and Recreation (DPR)
##### F6=Complaint Referred to Department of Transportation (DOT)
##### B2=OATH Summons Prepared and Attempt to Serve will be Made
##### C2=Inspector Unable to Gain Access – 2nd Final Attempt
##### J6=Sign Moratorium 2019
##### H3=Building Violation Issued for Failure to Obey Stop Work Order★
##### L1=Partial Stop Work Order
##### D5=Complaint Assigned to Emergency Response Team
##### F2=Complaint Referred to NYS Division of Housing and Community Renewal (DHCR)

In [96]:
target_code3 = ['A8', 'A1', 'A9', 'H3']
filtered_merged_df3 = merged_df3[merged_df3['disposition_code'].isin(target_code3)]
filtered_merged_df3

,building_name,pops_number,building_address_with_zip,year_completed,public_space_type,total_sf,size_required,hour_of_access_required,amenities_required,physically_disabled,...,infraction_code6,section_law_description6,infraction_code7,section_law_description7,infraction_code8,section_law_description8,infraction_code9,section_law_description9,infraction_code10,section_law_description10
0,NaN,M010025,"55 WATER STREET, New York, NY 10041",1970,Arcade; Elevated Plaza; Plaza,85046.0,Arcade 10254.00 sf; Elevated Plaza 41485.00 sf...,24 Hours; Closing for Events; Restricted Hours,Escalator; Food Service; Lighting; None; Other...,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,M010025,"55 WATER STREET, New York, NY 10041",1970,Arcade; Elevated Plaza; Plaza,85046.0,Arcade 10254.00 sf; Elevated Plaza 41485.00 sf...,24 Hours; Closing for Events; Restricted Hours,Escalator; Food Service; Lighting; None; Other...,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,M010025,"55 WATER STREET, New York, NY 10041",1970,Arcade; Elevated Plaza; Plaza,85046.0,Arcade 10254.00 sf; Elevated Plaza 41485.00 sf...,24 Hours; Closing for Events; Restricted Hours,Escalator; Food Service; Lighting; None; Other...,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,M010025,"55 WATER STREET, New York, NY 10041",1970,Arcade; Elevated Plaza; Plaza,85046.0,Arcade 10254.00 sf; Elevated Plaza 41485.00 sf...,24 Hours; Closing for Events; Restricted Hours,Escalator; Food Service; Lighting; None; Other...,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,M010025,"55 WATER STREET, New York, NY 10041",1970,Arcade; Elevated Plaza; Plaza,85046.0,Arcade 10254.00 sf; Elevated Plaza 41485.00 sf...,24 Hours; Closing for Events; Restricted Hours,Escalator; Food Service; Lighting; None; Other...,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111224,NaN,K150001,"1809 EMMONS AVENUE, Brooklyn, NY 11235",NaN,'Plaza',<NA>,NaN,NaN,NaN,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111225,NaN,K150001,"1809 EMMONS AVENUE, Brooklyn, NY 11235",NaN,'Plaza',<NA>,NaN,NaN,NaN,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111226,NaN,K150001,"1809 EMMONS AVENUE, Brooklyn, NY 11235",NaN,'Plaza',<NA>,NaN,NaN,NaN,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111227,NaN,K150001,"1809 EMMONS AVENUE, Brooklyn, NY 11235",NaN,'Plaza',<NA>,NaN,NaN,NaN,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111228,NaN,K150001,"1809 EMMONS AVENUE, Brooklyn, NY 11235",NaN,'Plaza',<NA>,NaN,NaN,NaN,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### issue_date

In [105]:
filtered_merged_df3['issue_date'] = pd.to_datetime(filtered_merged_df3['issue_date'].replace('0', pd.NA),format='%Y%m%d')
filtered_merged_df3.sort_values('issue_date')['issue_date'].tolist()
filtered_merged_df3 = filtered_merged_df3[
    filtered_merged_df3['issue_date'] >= '2000-01-01'
]
filtered_merged_df3

,building_name,pops_number,building_address_with_zip,year_completed,public_space_type,total_sf,size_required,hour_of_access_required,amenities_required,physically_disabled,...,infraction_code6,section_law_description6,infraction_code7,section_law_description7,infraction_code8,section_law_description8,infraction_code9,section_law_description9,infraction_code10,section_law_description10
0,NaN,M010025,"55 WATER STREET, New York, NY 10041",1970,Arcade; Elevated Plaza; Plaza,85046.0,Arcade 10254.00 sf; Elevated Plaza 41485.00 sf...,24 Hours; Closing for Events; Restricted Hours,Escalator; Food Service; Lighting; None; Other...,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,M010025,"55 WATER STREET, New York, NY 10041",1970,Arcade; Elevated Plaza; Plaza,85046.0,Arcade 10254.00 sf; Elevated Plaza 41485.00 sf...,24 Hours; Closing for Events; Restricted Hours,Escalator; Food Service; Lighting; None; Other...,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,M010025,"55 WATER STREET, New York, NY 10041",1970,Arcade; Elevated Plaza; Plaza,85046.0,Arcade 10254.00 sf; Elevated Plaza 41485.00 sf...,24 Hours; Closing for Events; Restricted Hours,Escalator; Food Service; Lighting; None; Other...,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,M010025,"55 WATER STREET, New York, NY 10041",1970,Arcade; Elevated Plaza; Plaza,85046.0,Arcade 10254.00 sf; Elevated Plaza 41485.00 sf...,24 Hours; Closing for Events; Restricted Hours,Escalator; Food Service; Lighting; None; Other...,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,M010025,"55 WATER STREET, New York, NY 10041",1970,Arcade; Elevated Plaza; Plaza,85046.0,Arcade 10254.00 sf; Elevated Plaza 41485.00 sf...,24 Hours; Closing for Events; Restricted Hours,Escalator; Food Service; Lighting; None; Other...,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111224,NaN,K150001,"1809 EMMONS AVENUE, Brooklyn, NY 11235",NaN,'Plaza',<NA>,NaN,NaN,NaN,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111225,NaN,K150001,"1809 EMMONS AVENUE, Brooklyn, NY 11235",NaN,'Plaza',<NA>,NaN,NaN,NaN,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111226,NaN,K150001,"1809 EMMONS AVENUE, Brooklyn, NY 11235",NaN,'Plaza',<NA>,NaN,NaN,NaN,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111227,NaN,K150001,"1809 EMMONS AVENUE, Brooklyn, NY 11235",NaN,'Plaza',<NA>,NaN,NaN,NaN,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111228,NaN,K150001,"1809 EMMONS AVENUE, Brooklyn, NY 11235",NaN,'Plaza',<NA>,NaN,NaN,NaN,Full/Partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Number of Buildings in Violation

In [106]:
summary3 = (
    filtered_merged_df3.groupby(
        ['bin']
        )['disposition_code']
    .value_counts()
    .unstack(fill_value=0)
    .reset_index()
)
summary3['total_violation'] = (summary3[['A1', 'A8', 'A9', 'H3']].sum(axis=1))
summary3

disposition_code      bin  A1   A8  A9  H3  total_violation
0                 1000018   0   18   0   0               18
1                 1000020   0   75   0   0               75
2                 1000793   0  768   0   0              768
3                 1000804   0  185   0   0              185
4                 1000807   0  183   0   0              183
..                    ...  ..  ...  ..  ..              ...
275               3319419   0   11   0   0               11
276               3393804   0   63   0   0               63
277               4307108   0    1   0   0                1
278               4607310   0   30   0   0               30
279               4615634   0   54   0   0               54

[280 rows x 6 columns]

### data cleaning

In [124]:
building_info3 = (
    filtered_merged_df3[
        [
            'bin',
            'building_name',
            'building_address_with_zip',
            'year_completed',
            'public_space_type',
            'hour_of_access_required',
            'size_required',
            'total_sf',
            'amenities_required',
            'physically_disabled',
            'developer',
            'complaint_number',
            'penality_imposed',
            'amount_paid',
            'latitude',
            'longitude'
        ]
    ]
    .drop_duplicates('bin')
)

summary_final3 = pd.merge(summary3,
    building_info3,
    on='bin',
    how='left'
)

date_range3 = (
    filtered_merged_df3.groupby('bin')['issue_date']
    .agg(
        first_issue_date='min',
        last_issue_date='max'
    )
        .reset_index()
)

cleaned_summary3 = pd.merge(summary_final3, date_range3, on='bin', how='left')
cleaned_summary3.to_csv('merged_POPS_DOB_ECB.csv', index=False)

In [118]:
cleaned_summary3.sort_values('amount_paid', ascending=False)

,bin,A1,A8,A9,H3,total_violation,building_name,building_address_with_zip,year_completed,public_space_type,...,amenities_required,physically_disabled,developer,complaint_number,penality_imposed,amount_paid,latitude,longitude,first_issue_date,last_issue_date
273,3247051,0,168,0,0,168,NaN,"1809 EMMONS AVENUE, Brooklyn, NY 11235",NaN,'Plaza',...,NaN,Full/Partial,NaN,3939566,4000,862,40.583936,-73.950173,2003-09-16,2025-10-10
102,1035407,0,52,0,0,52,NaN,"575 FIFTH AVENUE, New York, NY 10017",1983,Covered Pedestrian Space,...,Artwork; Climate Control; Drinking Fountain; F...,Full/Partial,575 Fifth Associates,1500511,800,800,40.756268,-73.978242,2007-07-17,2024-08-01
138,1038549,0,31,0,0,31,NaN,"885 THIRD AVENUE, New York, NY 10022",1985,Pedestrian Circulation Space,...,Lighting; Planting; Plaque/Sign; Subway; Trees...,Full/Partial,Gerald Hines,1594811,800,800,40.757885,-73.968777,2003-01-02,2026-04-20
115,1036176,0,10,0,0,10,Two Grand Central Tower,"140 EAST 45 STREET, New York, NY 10017",1982,Arcade; Sidewalk Widening; Urban Plaza,...,Lighting; Litter Receptacles; Planting; Plaque...,Full/Partial,Harry Macklowe,1511152,800,800,40.752748,-73.9741,2001-08-16,2019-11-15
58,1021933,0,50,0,0,50,Whitney,"311 EAST 38 STREET, New York, NY 10016",1984,Residential Plaza,...,Bicycle Parking; Drinking Fountain; Lighting; ...,Full/Partial,NaN,1699180,800,800,40.747242,-73.973221,2003-05-12,2025-07-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,1038517,0,195,0,0,195,NaN,"875 THIRD AVENUE, New York, NY 10022",1980,Arcade; Covered Pedestrian Space; Open Space; ...,...,Climate Control; Escalator; Food Service; Othe...,Full/Partial,Madison Equities,1649980,0,0,40.757218,-73.969196,2000-05-23,2026-03-19
141,1038577,0,17,0,0,17,NaN,"919 THIRD AVENUE, New York, NY 10022",1970,Plaza,...,None,Full/Partial,NaN,1702498,0,0,40.758963,-73.967589,2001-12-05,2026-03-25
142,1038674,0,13,0,0,13,International Plaza,"303 EAST 43 STREET, New York, NY 10017",1984,Residential Plaza,...,Bicycle Parking; Drinking Fountain; Lighting; ...,Full/Partial,NaN,1668371,0,0,40.75056,-73.971256,2003-02-10,2023-06-28
143,1038781,0,6,0,0,6,Delegate,"301 EAST 45 STREET, New York, NY 10017",1979,Plaza,...,None,Full/Partial,NaN,1594984,0,0,40.751775,-73.970372,2009-01-10,2025-02-19
140,1038575,0,84,28,0,112,Brevard,"245 EAST 54 STREET, New York, NY 10022",1974,Plaza; Residential Plaza,...,Bicycle Parking; Drinking Fountain; Food Servi...,Full/Partial,NaN,1091309,0,0,40.757849,-73.966795,2000-08-15,2025-10-16

In [135]:
cleaned_summary3['amount_paid'].value_counts()

amount_paid
0        113
400       17
500       17
1000      15
1200      13
250       12
800       10
1600       9
180        9
350        7
2400       7
200        5
100        4
4000       4
2000       3
360        2
2500       2
300        2
1250       2
1500       2
227        1
5000       1
532        1
12000      1
5101       1
405        1
2075       1
4356       1
4826       1
370        1
150        1
1430       1
3000       1
480        1
4500       1
1429       1
1160       1
1601       1
606        1
281        1
254        1
10041      1
862        1
3623       1
2523       1
Name: count, dtype: int64